/**
 * \file vkblas.c
 * \brief Vulkan-native BLAS implementation.
 *
 * Implements context lifecycle, lazy pipeline creation with caching,
 * capability-based shader tier selection, and GEMM dispatch for f32
 * (sgemm, sgemm_strided_batched, sgemm_batched).
 */

#include "vkblas.h"
#include "vkblas_internal.h"
#include "shaders_spv.h"

#include <string.h>
#include <stdio.h>
#include <stdlib.h>

/* ── bf16 -> f32 conversion (CPU side) ──────────────────────────────────── */

/* bfloat16 is the high 16 bits of an IEEE-754 f32; zero the low mantissa
   bits and reinterpret. Handles 0/inf/nan exactly (all share the exponent). */
static float vkblas_bf16_to_f32(uint16_t b)
{
    uint32_t fbits = (uint32_t)b << 16;
    float f;
    memcpy(&f, &fbits, sizeof(f));
    return f;
}

/* ── f16 -> f32 conversion (CPU side) ───────────────────────────────────── */

static float vkblas_f16_to_f32(uint16_t h)
{
    uint32_t sign = (uint32_t)(h & 0x8000u) << 16;
    uint32_t exp  = (uint32_t)(h & 0x7C00u) >> 10;
    uint32_t man  = (uint32_t)(h & 0x03FFu);
    uint32_t fbits;

    if (exp == 0) {
        if (man == 0) {
            fbits = sign;                                   /* +/-0 */
        } else {
            /* subnormal: normalize into the normal exponent range */
            int e = 1;
            while ((man & 0x0400u) == 0u) { man <<= 1; --e; }
            man &= 0x03FFu;
            fbits = sign | ((uint32_t)(e + 112) << 23) | (man << 13);
        }
    } else if (exp == 0x1Fu) {
        fbits = sign | 0x7F800000u | (man << 13);           /* inf/nan */
    } else {
        fbits = sign | ((exp + 112u) << 23) | (man << 13);
    }

    float f;
    memcpy(&f, &fbits, sizeof(f));
    return f;
}

/* ── Specialization constant values ──────────────────────────────────────── */

#define VKBLAS_TILE_M 16
#define VKBLAS_TILE_N 16
#define VKBLAS_TILE_K 16

/* ── Specialization constant map (same for all f32 tiers) ────────────────── */

static VkSpecializationMapEntry vkblas_sc_map[] = {
    { 0, 0, sizeof(uint32_t) },   /* TILE_M */
    { 1, 4, sizeof(uint32_t) },   /* TILE_N */
    { 2, 8, sizeof(uint32_t) },   /* TILE_K */
    { 3, 12, sizeof(uint32_t) },  /* SG_WIDTH (subgroup) */
    { 4, 16, sizeof(uint32_t) },  /* CM_MSIZE (coopmatrix) */
    { 5, 20, sizeof(uint32_t) },  /* CM_NSIZE (coopmatrix) */
    { 6, 24, sizeof(uint32_t) },  /* CM_KSIZE (coopmatrix) */
};

/* ── Forward declarations for SPIR-V blobs ────────────────────────────────── */
/* Declared in shaders_spv.h — generated by compile_shaders.ps1 */

/* ── Hash function ───────────────────────────────────────────────────────── */

uint64_t vkblas_hash_key(uint32_t dt, uint32_t tA, uint32_t tB,
                         uint32_t strided, uint32_t tier)
{
    uint64_t h = (uint64_t)dt;
    h = h * 31 + tA;
    h = h * 31 + tB;
    h = h * 31 + strided;
    h = h * 31 + tier;
    h = h * 31 + VKBLAS_TILE_M;
    h = h * 31 + VKBLAS_TILE_N;
    h = h * 31 + VKBLAS_TILE_K;
    return h;
}

/* ── Shader blob selector ────────────────────────────────────────────────── */

/* Select the SPIR-V blob for an exact (data_type, tier) pair. Returns NULL
   when that combination has no shader (e.g. f16/f64 only exist at baseline);
   the caller falls back to lower tiers per the AGENTS.md fallback chain. */
static const uint32_t* vkblas_select_spirv(VkBLASContext* ctx,
                                           uint32_t data_type,
                                           VkBLASTier_t tier,
                                           size_t* out_size)
{
    (void)ctx;
    switch (tier) {
    case VKBLAS_TIER_COOPMATRIX:
        /* Real coop-matrix shader is dormant unless explicitly enabled via
           VAIT_COOPMATRIX; AMD 26.7.1 crashes on coopMatMulAddKHR pipelines.
           When disabled, fall through to the shared-memory tiers below. */
        if (ctx->use_coopmat != VK_TRUE)
            return NULL;
        switch (data_type) {
        case VKBLAS_DTYPE_F32:
            *out_size = vkblas_spv_coopmatrix_gemm_f32_size;
            return vkblas_spv_coopmatrix_gemm_f32;
        default:
            return NULL;
        }
    case VKBLAS_TIER_SUBGROUP:
        switch (data_type) {
        case VKBLAS_DTYPE_F32:
            *out_size = vkblas_spv_subgroup_gemm_f32_size;
            return vkblas_spv_subgroup_gemm_f32;
        default:
            return NULL;
        }
    case VKBLAS_TIER_BASELINE:
        switch (data_type) {
        case VKBLAS_DTYPE_F32:
            *out_size = vkblas_spv_baseline_gemm_f32_size;
            return vkblas_spv_baseline_gemm_f32;
        case VKBLAS_DTYPE_F16:
            *out_size = vkblas_spv_baseline_gemm_f16_size;
            return vkblas_spv_baseline_gemm_f16;
        case VKBLAS_DTYPE_BF16:
            *out_size = vkblas_spv_baseline_gemm_bf16_size;
            return vkblas_spv_baseline_gemm_bf16;
        case VKBLAS_DTYPE_F64:
            *out_size = vkblas_spv_baseline_gemm_f64_size;
            return vkblas_spv_baseline_gemm_f64;
        case VKBLAS_DTYPE_QGEMM_Q8_0:
            *out_size = vkblas_spv_baseline_qgemm_q8_0_size;
            return vkblas_spv_baseline_qgemm_q8_0;
        case VKBLAS_DTYPE_QGEMM_Q4K:
            *out_size = vkblas_spv_baseline_qgemm_q4k_size;
            return vkblas_spv_baseline_qgemm_q4k;
        case VKBLAS_DTYPE_QGEMM_Q4_0:
            *out_size = vkblas_spv_baseline_qgemm_q4_0_size;
            return vkblas_spv_baseline_qgemm_q4_0;
        case VKBLAS_DTYPE_QGEMM_Q5K:
            *out_size = vkblas_spv_baseline_qgemm_q5k_size;
            return vkblas_spv_baseline_qgemm_q5k;
        case VKBLAS_DTYPE_QGEMM_Q6K:
            *out_size = vkblas_spv_baseline_qgemm_q6k_size;
            return vkblas_spv_baseline_qgemm_q6k;
        case VKBLAS_DTYPE_QGEMM_Q3K:
            *out_size = vkblas_spv_baseline_qgemm_q3k_size;
            return vkblas_spv_baseline_qgemm_q3k;
        case VKBLAS_DTYPE_QGEMM_IQ4XS:
            *out_size = vkblas_spv_baseline_qgemm_iq4xs_size;
            return vkblas_spv_baseline_qgemm_iq4xs;
        default:
            return NULL;
        }
    default:
        return NULL;
    }
}

/* ── Specialization constant data ─────────────────────────────────────────── */

static void vkblas_fill_sc_data(uint32_t* data, VkBLASTier_t tier)
{
    (void)tier;
    data[0] = VKBLAS_TILE_M;   /* constant_id 0 */
    data[1] = VKBLAS_TILE_N;   /* constant_id 1 */
    data[2] = VKBLAS_TILE_K;   /* constant_id 2 */
    data[3] = 32;              /* SG_WIDTH (constant_id 3) */
    data[4] = 16;              /* CM_MSIZE (constant_id 4) */
    data[5] = 16;              /* CM_NSIZE (constant_id 5) */
    data[6] = 16;              /* CM_KSIZE (constant_id 6) */
}

/* ── Pipeline layout ─────────────────────────────────────────────────────── */

VkPipelineLayout vkblas_get_pipeline_layout(VkBLASContext* ctx)
{
    return ctx->pipeline_layout;
}

/* ── Shader module ───────────────────────────────────────────────────────── */

VkResult vkblas_load_shader_module(VkDevice device,
                                   const uint32_t* spirv, size_t spirv_words,
                                   VkShaderModule* out_module)
{
    VkShaderModuleCreateInfo smci = {
        .sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        .pNext    = NULL,
        .flags    = 0,
        .codeSize = spirv_words,
        .pCode    = spirv,
    };
    return vkCreateShaderModule(device, &smci, NULL, out_module);
}

/* ── Descriptor set layout ────────────────────────────────────────────────── */

static VkResult vkblas_create_set_layout(VkBLASContext* ctx)
{
    VkDescriptorSetLayoutBinding bindings[4] = {
        { 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, NULL },
        { 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, NULL },
        { 2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, NULL },
        { 3, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, NULL },
    };

    VkDescriptorSetLayoutCreateInfo dslci = {
        .sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        .bindingCount = 4,
        .pBindings    = bindings,
    };
    return vkCreateDescriptorSetLayout(ctx->device, &dslci, NULL, &ctx->set_layout);
}

/* ── Pipeline cache lookup / creation ─────────────────────────────────────── */

static uint32_t vkblas_hash_to_slot(uint64_t key)
{
    /* Simple multiplicative hash + modulo (power-of-two table) */
    key ^= key >> 32;
    key *= 0x9e3779b97f4a7c15ULL;
    return (uint32_t)(key & (VKBLAS_MAX_PIPELINES - 1));
}

static VkPipeline vkblas_get_cached_pipeline_tier(VkBLASContext* ctx,
                                                  uint32_t data_type,
                                                  VkBool32 transA,
                                                  VkBool32 transB,
                                                  VkBool32 is_strided,
                                                  VkBLASTier_t tier)
{
    uint64_t key = vkblas_hash_key(data_type, transA, transB, is_strided,
                                   (uint32_t)tier);
    uint32_t slot = vkblas_hash_to_slot(key);

    for (uint32_t i = 0; i < VKBLAS_MAX_PIPELINES; ++i) {
        uint32_t idx = (slot + i) & (VKBLAS_MAX_PIPELINES - 1);
        if (!ctx->pipelines[idx].valid)
            break;
        if (ctx->pipelines[idx].key == key)
            return ctx->pipelines[idx].pipeline;
    }
    return VK_NULL_HANDLE;
}

VkPipeline vkblas_get_cached_pipeline(VkBLASContext* ctx,
                                       uint32_t data_type,
                                       VkBool32 transA, VkBool32 transB,
                                       VkBool32 is_strided)
{
    /* Search from the active tier down so a cached lower-tier fallback
       (e.g. f16 baseline) is found even when a higher tier is active. */
    int t = (int)ctx->active_tier;
    while (t >= (int)VKBLAS_TIER_BASELINE) {
        VkPipeline p = vkblas_get_cached_pipeline_tier(ctx, data_type, transA,
                                                       transB, is_strided,
                                                       (VkBLASTier_t)t);
        if (p != VK_NULL_HANDLE)
            return p;
        --t;
    }
    return VK_NULL_HANDLE;
}

VkResult vkblas_ensure_pipeline(VkBLASContext* ctx,
                                uint32_t data_type,
                                uint32_t transA, uint32_t transB,
                                uint32_t is_strided,
                                VkPipeline* out_pipeline)
{
    /* Try cache first (searches all tiers) */
    VkPipeline cached = vkblas_get_cached_pipeline(ctx, data_type,
                                                   transA, transB, is_strided);
    if (cached != VK_NULL_HANDLE) {
        *out_pipeline = cached;
        return VK_SUCCESS;
    }

    /* Attempt to create a pipeline, trying the active tier first and
       falling back to lower tiers (per AGENTS.md fallback chain). */
    VkResult last_result = VK_ERROR_FEATURE_NOT_PRESENT;

    int t = (int)ctx->active_tier;
    while (t >= (int)VKBLAS_TIER_BASELINE) {
        VkBLASTier_t tier = (VkBLASTier_t)t;

        /* Select SPIR-V blob for this tier */
        size_t spirv_size = 0;
        const uint32_t* spirv = vkblas_select_spirv(ctx, data_type, tier,
                                                    &spirv_size);
        if (spirv == NULL) {
            --t;
            continue;
        }

        /* Create shader module */
        VkShaderModule sm;
        VkResult r = vkblas_load_shader_module(ctx->device, spirv,
                                               spirv_size, &sm);
        if (r != VK_SUCCESS) {
            last_result = r;
            --t;
            continue;
        }

        /* Specialization constants */
        uint32_t sc_data[7];
        vkblas_fill_sc_data(sc_data, tier);

        VkSpecializationInfo si = {
            .mapEntryCount = 7,
            .pMapEntries   = vkblas_sc_map,
            .dataSize      = sizeof(sc_data),
            .pData         = sc_data,
        };

        VkComputePipelineCreateInfo cpci = {
            .sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
            .stage  = {
                .sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                .stage  = VK_SHADER_STAGE_COMPUTE_BIT,
                .module = sm,
                .pName  = "main",
                .pSpecializationInfo = &si,
            },
            .layout = ctx->pipeline_layout,
        };

        VkPipeline pipeline;
        r = vkCreateComputePipelines(ctx->device, ctx->pipeline_cache, 1, &cpci,
                                      NULL, &pipeline);
        vkDestroyShaderModule(ctx->device, sm, NULL);
        if (r != VK_SUCCESS) {
            last_result = r;
            --t;
            continue;
        }

        /* Insert into cache under the tier actually used */
        uint64_t key = vkblas_hash_key(data_type, transA, transB, is_strided,
                                       (uint32_t)tier);
        uint32_t slot = vkblas_hash_to_slot(key);

        for (uint32_t i = 0; i < VKBLAS_MAX_PIPELINES; ++i) {
            uint32_t idx = (slot + i) & (VKBLAS_MAX_PIPELINES - 1);
            if (!ctx->pipelines[idx].valid) {
                ctx->pipelines[idx].key        = key;
                ctx->pipelines[idx].pipeline   = pipeline;
                ctx->pipelines[idx].layout     = ctx->pipeline_layout;
                ctx->pipelines[idx].data_type  = data_type;
                ctx->pipelines[idx].transA     = transA;
                ctx->pipelines[idx].transB     = transB;
                ctx->pipelines[idx].is_strided = is_strided;
                ctx->pipelines[idx].tier       = (uint32_t)tier;
                ctx->pipelines[idx].valid      = 1;
                ctx->pipeline_count++;
                break;
            }
        }

        *out_pipeline = pipeline;
        return VK_SUCCESS;
    }

    return last_result;
}

/* ── Descriptor set allocation ────────────────────────────────────────────── */

VkResult vkblas_alloc_descriptor_set(VkBLASContext* ctx, VkDescriptorSet* out)
{
    VkDescriptorSetAllocateInfo dsai = {
        .sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
        .descriptorPool     = ctx->descriptor_pool,
        .descriptorSetCount = 1,
        .pSetLayouts        = &ctx->set_layout,
    };
    return vkAllocateDescriptorSets(ctx->device, &dsai, out);
}

/* ── Descriptor set write ─────────────────────────────────────────────────── */

void vkblas_write_descriptor_set(VkBLASContext* ctx, VkDescriptorSet ds,
                                 VkBuffer A, VkBuffer B, VkBuffer C, VkBuffer D)
{
    VkDescriptorBufferInfo bi[4] = {
        { A, 0, VK_WHOLE_SIZE },
        { B, 0, VK_WHOLE_SIZE },
        { C, 0, VK_WHOLE_SIZE },
        { D, 0, VK_WHOLE_SIZE },
    };

    VkWriteDescriptorSet writes[4] = {
        { VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, .dstSet = ds, .dstBinding = 0,
          .descriptorCount = 1, .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
          .pBufferInfo = &bi[0] },
        { VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, .dstSet = ds, .dstBinding = 1,
          .descriptorCount = 1, .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
          .pBufferInfo = &bi[1] },
        { VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, .dstSet = ds, .dstBinding = 2,
          .descriptorCount = 1, .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
          .pBufferInfo = &bi[2] },
        { VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, .dstSet = ds, .dstBinding = 3,
          .descriptorCount = 1, .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
          .pBufferInfo = &bi[3] },
    };

    vkUpdateDescriptorSets(ctx->device, 4, writes, 0, NULL);
}

/* ── Push constants ───────────────────────────────────────────────────────── */

void vkblas_push_pc(VkCommandBuffer cmd, VkPipelineLayout layout,
                    const vkblas_push_constants_t* pc)
{
    vkCmdPushConstants(cmd, layout, VK_SHADER_STAGE_COMPUTE_BIT,
                       0, sizeof(vkblas_push_constants_t), pc);
}

/* ── Context lifecycle ────────────────────────────────────────────────────── */

VkResult vkblas_create_context(VkPhysicalDevice physicalDevice,
                               VkDevice device,
                               VkBLASContext** pContext)
{
    if (!pContext) return VK_ERROR_INITIALIZATION_FAILED;

    VkBLASContext* ctx = (VkBLASContext*)malloc(sizeof(VkBLASContext));
    if (!ctx) return VK_ERROR_OUT_OF_HOST_MEMORY;

    memset(ctx, 0, sizeof(*ctx));
    ctx->device = device;

    /* Pipeline cache via VKRuntime helper */
    VkResult r = vkr_create_pipeline_cache(device, &ctx->pipeline_cache);
    if (r != VK_SUCCESS) goto fail;

    /* Descriptor pool via VKRuntime helper */
    r = vkr_create_descriptor_pool(device, VKBLAS_MAX_PIPELINES,
                                   VKBLAS_MAX_PIPELINES, &ctx->descriptor_pool);
    if (r != VK_SUCCESS) goto fail;

    /* Descriptor set layout (lib-specific, stays local) */
    r = vkblas_create_set_layout(ctx);
    if (r != VK_SUCCESS) goto fail;

    /* Pipeline layout via VKRuntime helper; the push-constant range is
       lib-specific and stays local. */
    VkPushConstantRange pcr = {
        .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
        .offset     = 0,
        .size       = sizeof(vkblas_push_constants_t),
    };
    r = vkr_create_pipeline_layout(device, ctx->set_layout, 1, &pcr,
                                   &ctx->pipeline_layout);
    if (r != VK_SUCCESS) goto fail;

    /* Detect capabilities via VKRuntime (single implementation). */
    VkRuntimeCaps caps;
    r = vkr_detect_capabilities(physicalDevice, device, &caps);
    if (r != VK_SUCCESS) {
        /* Fall back to baseline if detection fails */
        ctx->active_tier = VKBLAS_TIER_BASELINE;
        ctx->has_subgroup = VK_FALSE;
        ctx->has_coop_matrix = VK_FALSE;
    } else {
        ctx->has_subgroup = caps.has_subgroup;
        ctx->has_coop_matrix = caps.has_coop_matrix;
        ctx->max_subgroup_size = caps.subgroup_size;
        ctx->max_compute_workgroup_size[0] = caps.max_workgroup_size[0];
        ctx->max_compute_workgroup_size[1] = caps.max_workgroup_size[1];
        ctx->max_compute_workgroup_size[2] = caps.max_workgroup_size[2];

        /* Driver-guarded cooperative-matrix path (see AGENTS.md): default OFF
           because the AMD 26.7.1 Windows driver hard-crashes
           (0xE06D7363) inside vkCreateComputePipelines for modules containing
           coopMatMulAddKHR. Enabled only when VAIT_COOPMATRIX is set. */
        ctx->use_coopmat = (getenv("VAIT_COOPMATRIX") != NULL) &&
                           (ctx->has_coop_matrix == VK_TRUE);
        if (ctx->use_coopmat && ctx->has_subgroup) {
            ctx->active_tier = VKBLAS_TIER_COOPMATRIX;
        } else if (ctx->has_subgroup) {
            ctx->active_tier = VKBLAS_TIER_SUBGROUP;
        } else {
            ctx->active_tier = VKBLAS_TIER_BASELINE;
        }
    }

    *pContext = ctx;
    return VK_SUCCESS;

fail:
    if (ctx->pipeline_cache)
        vkDestroyPipelineCache(device, ctx->pipeline_cache, NULL);
    if (ctx->descriptor_pool)
        vkDestroyDescriptorPool(device, ctx->descriptor_pool, NULL);
    if (ctx->set_layout)
        vkDestroyDescriptorSetLayout(device, ctx->set_layout, NULL);
    if (ctx->pipeline_layout)
        vkDestroyPipelineLayout(device, ctx->pipeline_layout, NULL);
    free(ctx);
    return r;
}

void vkblas_destroy_context(VkBLASContext* context)
{
    if (!context) return;

    for (uint32_t i = 0; i < VKBLAS_MAX_PIPELINES; ++i) {
        if (context->pipelines[i].valid)
            vkDestroyPipeline(context->device, context->pipelines[i].pipeline, NULL);
    }

    if (context->pipeline_cache)
        vkDestroyPipelineCache(context->device, context->pipeline_cache, NULL);
    if (context->descriptor_pool)
        vkDestroyDescriptorPool(context->device, context->descriptor_pool, NULL);
    if (context->set_layout)
        vkDestroyDescriptorSetLayout(context->device, context->set_layout, NULL);
    if (context->pipeline_layout)
        vkDestroyPipelineLayout(context->device, context->pipeline_layout, NULL);

    free(context);
}

uint32_t vkblas_get_arch_index(VkBLASContext* context)
{
    return (uint32_t)context->active_tier;
}

const char* vkblas_get_arch_name(VkBLASContext* context)
{
    switch (context->active_tier) {
    case VKBLAS_TIER_BASELINE:   return "baseline";
    case VKBLAS_TIER_SUBGROUP:   return "subgroup";
    case VKBLAS_TIER_COOPMATRIX: return "coopmatrix";
    default:                     return "unknown";
    }
}

/* ── Capability detection ─────────────────────────────────────────────────── */

VkResult vkblas_init_capabilities(VkBLASContext* ctx, VkPhysicalDevice pd)
{
    if (!ctx) return VK_ERROR_INITIALIZATION_FAILED;

    /* Single VKRuntime implementation: subgroup / cooperative-matrix /
       shaderInt64 detection plus push-desc fn load. */
    VkRuntimeCaps caps;
    VkResult r = vkr_detect_capabilities(pd, ctx->device, &caps);
    if (r != VK_SUCCESS) return r;

    ctx->has_subgroup = caps.has_subgroup;
    ctx->has_coop_matrix = caps.has_coop_matrix;
    ctx->max_subgroup_size = caps.subgroup_size;
    ctx->max_compute_workgroup_size[0] = caps.max_workgroup_size[0];
    ctx->max_compute_workgroup_size[1] = caps.max_workgroup_size[1];
    ctx->max_compute_workgroup_size[2] = caps.max_workgroup_size[2];

    /* Select highest tier.
       The cooperative-matrix tier is SELECTABLE but dormant by default: the
       AMD 26.7.1 Windows driver crashes the whole process (0xE06D7363) inside
       vkCreateComputePipelines when compiling a module that contains
       coopMatMulAddKHR. We therefore only route through the coopmatrix shader
       when the operator explicitly opts in via VAIT_COOPMATRIX. */
    ctx->use_coopmat = (getenv("VAIT_COOPMATRIX") != NULL) &&
                       (ctx->has_coop_matrix == VK_TRUE);
    if (ctx->use_coopmat && ctx->has_subgroup) {
        ctx->active_tier = VKBLAS_TIER_COOPMATRIX;
    } else if (ctx->has_subgroup) {
        ctx->active_tier = VKBLAS_TIER_SUBGROUP;
    } else {
        ctx->active_tier = VKBLAS_TIER_BASELINE;
    }

    return VK_SUCCESS;
}

void vkblas_flush_pipelines(VkBLASContext* ctx)
{
    for (uint32_t i = 0; i < VKBLAS_MAX_PIPELINES; ++i) {
        if (ctx->pipelines[i].valid) {
            vkDestroyPipeline(ctx->device, ctx->pipelines[i].pipeline, NULL);
            ctx->pipelines[i].valid = 0;
        }
    }
    ctx->pipeline_count = 0;
}

/* ── Pointer mode ─────────────────────────────────────────────────────────── */

VkResult vkblas_set_pointer_mode(VkBLASContext* ctx, VkBLASPointerMode_t mode)
{
    if (!ctx) return VK_ERROR_INITIALIZATION_FAILED;
    ctx->pointer_mode = mode;
    return VK_SUCCESS;
}

VkBLASPointerMode_t vkblas_get_pointer_mode(VkBLASContext* ctx)
{
    if (!ctx) return VKBLAS_POINTER_MODE_HOST;
    return ctx->pointer_mode;
}

/* ── GEMM dispatch (generic over dtype) ──────────────────────────────────── */

/* Fill alpha/beta push-constant scalars for the data type.
   - f32: stored directly in pc.alpha/pc.beta.
   - f16: converted to f32 (exact) and stored in pc.alpha/pc.beta.
   - f64: raw double bits packed into the 8-byte slots at offsets 12..19
     (pc.alpha/pc.beta) and 76..83 (pc._pad2/pc._pad3); the f64 shader
     recombines them with packDouble2x32. */
static void vkblas_fill_scalars(uint32_t dtype, vkblas_push_constants_t* pc,
                                const void* alpha, const void* beta)
{
    pc->beta_is_zero = 0;

    switch (dtype) {
    case VKBLAS_DTYPE_F64: {
        double av = (alpha != NULL) ? *(const double*)alpha : 1.0;
        double bv = (beta  != NULL) ? *(const double*)beta  : 0.0;
        memcpy(&pc->alpha, &av, sizeof(av));   /* offsets 12..19 */
        memcpy(&pc->_pad2, &bv, sizeof(bv));   /* offsets 76..83 */
        if (bv == 0.0)
            pc->beta_is_zero = 1;
        break;
    }
    case VKBLAS_DTYPE_BF16: {
        /* bf16 alpha/beta: uint16 bits; promote to f32 via bits<<16. */
        float av = (alpha != NULL)
            ? vkblas_bf16_to_f32(*(const uint16_t*)alpha) : 1.0f;
        float bv = (beta != NULL)
            ? vkblas_bf16_to_f32(*(const uint16_t*)beta) : 0.0f;
        pc->alpha = av;
        pc->beta  = bv;
        if (bv == 0.0f)
            pc->beta_is_zero = 1;
        break;
    }
    case VKBLAS_DTYPE_F16: {
        float av = (alpha != NULL)
            ? vkblas_f16_to_f32(*(const uint16_t*)alpha) : 1.0f;
        float bv = (beta != NULL)
            ? vkblas_f16_to_f32(*(const uint16_t*)beta) : 0.0f;
        pc->alpha = av;
        pc->beta  = bv;
        if (bv == 0.0f)
            pc->beta_is_zero = 1;
        break;
    }
    default: /* f32 */
        pc->alpha = (alpha != NULL) ? *(const float*)alpha : 1.0f;
        pc->beta  = (beta  != NULL) ? *(const float*)beta  : 0.0f;
        if (pc->beta == 0.0f)
            pc->beta_is_zero = 1;
        break;
    }
}

/* Shared dispatch for every GEMM family member. alpha/beta are opaque
   pointers whose element type follows `dtype`. */
static VkResult vkblas_gemm_common(VkBLASContext*  ctx,
                                   VkCommandBuffer  cmd,
                                   VkBLASOperation_t transA,
                                   VkBLASOperation_t transB,
                                   int32_t          m,
                                   int32_t          n,
                                   int32_t          k,
                                   uint32_t         dtype,
                                   const void*      alpha,
                                   VkBuffer         A,
                                   int32_t          lda,
                                   VkBuffer         B,
                                   int32_t          ldb,
                                   const void*      beta,
                                   VkBuffer         C,
                                   int32_t          ldc,
                                   VkBuffer         D,
                                   int32_t          ldd,
                                   uint32_t         strideA,
                                   uint32_t         strideB,
                                   uint32_t         strideC,
                                   uint32_t         strideD,
                                   int32_t          batchCount,
                                   VkBool32         is_strided)
{
    /* Ensure pipeline exists */
    uint32_t tA = (transA == VKBLAS_OP_N) ? 0 : 1;
    uint32_t tB = (transB == VKBLAS_OP_N) ? 0 : 1;

    VkPipeline pipeline = VK_NULL_HANDLE;
    VkResult r = vkblas_ensure_pipeline(ctx, dtype, tA, tB, is_strided,
                                        &pipeline);
    if (r != VK_SUCCESS)
        return r;

    /* Allocate descriptor set */
    VkDescriptorSet ds;
    r = vkblas_alloc_descriptor_set(ctx, &ds);
    if (r != VK_SUCCESS)
        return r;

    vkblas_write_descriptor_set(ctx, ds, A, B,
                                (C != VK_NULL_HANDLE) ? C : A, D);
    /* Use A as dummy for C when beta==0 (read-only binding won't be accessed) */

    /* Bind pipeline and descriptor set */
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
                            ctx->pipeline_layout, 0, 1, &ds, 0, NULL);

    /* Push constants */
    vkblas_push_constants_t pc = {0};
    pc.m = (uint32_t)m;
    pc.n = (uint32_t)n;
    pc.k = (uint32_t)k;
    vkblas_fill_scalars(dtype, &pc, alpha, beta);
    pc.lda = (uint32_t)lda;
    pc.ldb = (uint32_t)ldb;
    pc.ldc = (uint32_t)ldc;
    pc.ldd = (uint32_t)ldd;
    pc.transA = (int32_t)tA;
    pc.transB = (int32_t)tB;
    pc.strideA = strideA;
    pc.strideB = strideB;
    pc.strideC = strideC;
    pc.strideD = strideD;
    pc.batchCount = (uint32_t)batchCount;
    vkblas_push_pc(cmd, ctx->pipeline_layout, &pc);

    /* Compute grid: one workgroup per TILE_M × TILE_N output block */
    uint32_t gridX = (uint32_t)((m + VKBLAS_TILE_M - 1) / VKBLAS_TILE_M);
    uint32_t gridY = (uint32_t)((n + VKBLAS_TILE_N - 1) / VKBLAS_TILE_N);
    uint32_t gridZ = batchCount > 0 ? (uint32_t)batchCount : 1;

    vkCmdDispatch(cmd, gridX, gridY, gridZ);

    return VK_SUCCESS;
}

VkResult vkblas_sgemm(VkBLASContext*  context,
                      VkCommandBuffer cmd,
                      VkBLASOperation_t transA,
                      VkBLASOperation_t transB,
                      int32_t           m,
                      int32_t           n,
                      int32_t           k,
                      const float*      alpha,
                      VkBuffer          A,
                      int32_t           lda,
                      VkBuffer          B,
                      int32_t           ldb,
                      const float*      beta,
                      VkBuffer          C,
                      int32_t           ldc,
                      VkBuffer          D,
                      int32_t           ldd)
{
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;  /* no-op for zero-dim matrices */

    return vkblas_gemm_common(context, cmd, transA, transB,
                              m, n, k, VKBLAS_DTYPE_F32,
                              (const void*)alpha, A, lda, B, ldb,
                              (const void*)beta, C, ldc, D, ldd,
                              0, 0, 0, 0, 1, VK_FALSE);
}

VkResult vkblas_sgemm_strided_batched(VkBLASContext*    context,
                                      VkCommandBuffer   cmd,
                                      VkBLASOperation_t transA,
                                      VkBLASOperation_t transB,
                                      int32_t           m,
                                      int32_t           n,
                                      int32_t           k,
                                      const float*      alpha,
                                      VkBuffer          A,
                                      int32_t           lda,
                                      int64_t           strideA,
                                      VkBuffer          B,
                                      int32_t           ldb,
                                      int64_t           strideB,
                                      const float*      beta,
                                      VkBuffer          C,
                                      int32_t           ldc,
                                      int64_t           strideC,
                                      VkBuffer          D,
                                      int32_t           ldd,
                                      int64_t           strideD,
                                      int32_t           batchCount)
{
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0 || batchCount <= 0)
        return VK_SUCCESS;

    /* Strides are in bytes in the API but elements in the shader */
    uint32_t elem_strideA = (uint32_t)(strideA / sizeof(float));
    uint32_t elem_strideB = (uint32_t)(strideB / sizeof(float));
    uint32_t elem_strideC = (uint32_t)(strideC / sizeof(float));
    uint32_t elem_strideD = (uint32_t)(strideD / sizeof(float));

    return vkblas_gemm_common(context, cmd, transA, transB,
                              m, n, k, VKBLAS_DTYPE_F32,
                              (const void*)alpha, A, lda, B, ldb,
                              (const void*)beta, C, ldc, D, ldd,
                              elem_strideA, elem_strideB,
                              elem_strideC, elem_strideD,
                              batchCount, VK_TRUE);
}

VkResult vkblas_sgemm_batched(VkBLASContext*    context,
                              VkCommandBuffer   cmd,
                              VkBLASOperation_t transA,
                              VkBLASOperation_t transB,
                              int32_t           m,
                              int32_t           n,
                              int32_t           k,
                              const float*      alpha,
                              const VkBLASBufferLoc* A,
                              int32_t           lda,
                              const VkBLASBufferLoc* B,
                              int32_t           ldb,
                              const float*      beta,
                              const VkBLASBufferLoc* C,
                              int32_t           ldc,
                              VkBLASBufferLoc*  D,
                              int32_t           ldd,
                              int32_t           batchCount)
{
    /* Batched GEMM with per-matrix buffer arrays: implement as a loop
       of single GEMMs, each with its own buffer bindings. This is not
       optimal but correct — the caller can use strided_batched for
       better performance when matrices are contiguous. */
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0 || batchCount <= 0)
        return VK_SUCCESS;

    for (int32_t b = 0; b < batchCount; ++b) {
        VkBuffer bufA = (A[b].buffer != VK_NULL_HANDLE) ? A[b].buffer : A->buffer;
        VkBuffer bufB = (B[b].buffer != VK_NULL_HANDLE) ? B[b].buffer : B->buffer;
        VkBuffer bufC = (C && C[b].buffer != VK_NULL_HANDLE) ? C[b].buffer : A->buffer;
        VkBuffer bufD = (D[b].buffer != VK_NULL_HANDLE) ? D[b].buffer : A->buffer;

        VkResult r = vkblas_gemm_common(context, cmd, transA, transB,
                                        m, n, k, VKBLAS_DTYPE_F32,
                                        (const void*)alpha,
                                        bufA, lda, bufB, ldb,
                                        (const void*)beta, bufC, ldc, bufD, ldd,
                                        0, 0, 0, 0, 1, VK_FALSE);
        if (r != VK_SUCCESS) return r;
    }
    return VK_SUCCESS;
}

/* ── Non-f32 GEMM variants ───────────────────────────────────────────────── *
 * dgemm (f64), hgemm (f16) and bgemm (bf16) all use the same dispatch
 * machinery as sgemm with a dtype selector (VKBLAS_DTYPE_F64 / F16 / BF16).
 * ─────────────────────────────────────────────────────────────────────────── */

VkResult vkblas_dgemm(VkBLASContext* context, VkCommandBuffer cmd,
                      VkBLASOperation_t transA, VkBLASOperation_t transB,
                      int32_t m, int32_t n, int32_t k, const double* alpha,
                      VkBuffer A, int32_t lda, VkBuffer B, int32_t ldb,
                      const double* beta, VkBuffer C, int32_t ldc,
                      VkBuffer D, int32_t ldd) {
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;

    return vkblas_gemm_common(context, cmd, transA, transB,
                              m, n, k, VKBLAS_DTYPE_F64,
                              (const void*)alpha, A, lda, B, ldb,
                              (const void*)beta, C, ldc, D, ldd,
                              0, 0, 0, 0, 1, VK_FALSE);
}

VkResult vkblas_dgemm_strided_batched(VkBLASContext* context, VkCommandBuffer cmd,
                                      VkBLASOperation_t transA, VkBLASOperation_t transB,
                                      int32_t m, int32_t n, int32_t k, const double* alpha,
                                      VkBuffer A, int32_t lda, int64_t strideA,
                                      VkBuffer B, int32_t ldb, int64_t strideB,
                                      const double* beta, VkBuffer C, int32_t ldc, int64_t strideC,
                                      VkBuffer D, int32_t ldd, int64_t strideD, int32_t batchCount) {
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0 || batchCount <= 0)
        return VK_SUCCESS;

    uint32_t elem_strideA = (uint32_t)(strideA / sizeof(double));
    uint32_t elem_strideB = (uint32_t)(strideB / sizeof(double));
    uint32_t elem_strideC = (uint32_t)(strideC / sizeof(double));
    uint32_t elem_strideD = (uint32_t)(strideD / sizeof(double));

    return vkblas_gemm_common(context, cmd, transA, transB,
                              m, n, k, VKBLAS_DTYPE_F64,
                              (const void*)alpha, A, lda, B, ldb,
                              (const void*)beta, C, ldc, D, ldd,
                              elem_strideA, elem_strideB,
                              elem_strideC, elem_strideD,
                              batchCount, VK_TRUE);
}

VkResult vkblas_hgemm(VkBLASContext* context, VkCommandBuffer cmd,
                      VkBLASOperation_t transA, VkBLASOperation_t transB,
                      int32_t m, int32_t n, int32_t k, const uint16_t* alpha,
                      VkBuffer A, int32_t lda, VkBuffer B, int32_t ldb,
                      const uint16_t* beta, VkBuffer C, int32_t ldc,
                      VkBuffer D, int32_t ldd) {
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;

    return vkblas_gemm_common(context, cmd, transA, transB,
                              m, n, k, VKBLAS_DTYPE_F16,
                              (const void*)alpha, A, lda, B, ldb,
                              (const void*)beta, C, ldc, D, ldd,
                              0, 0, 0, 0, 1, VK_FALSE);
}

VkResult vkblas_hgemm_strided_batched(VkBLASContext* context, VkCommandBuffer cmd,
                                      VkBLASOperation_t transA, VkBLASOperation_t transB,
                                      int32_t m, int32_t n, int32_t k, const uint16_t* alpha,
                                      VkBuffer A, int32_t lda, int64_t strideA,
                                      VkBuffer B, int32_t ldb, int64_t strideB,
                                      const uint16_t* beta, VkBuffer C, int32_t ldc, int64_t strideC,
                                      VkBuffer D, int32_t ldd, int64_t strideD, int32_t batchCount) {
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0 || batchCount <= 0)
        return VK_SUCCESS;

    uint32_t elem_strideA = (uint32_t)(strideA / sizeof(uint16_t));
    uint32_t elem_strideB = (uint32_t)(strideB / sizeof(uint16_t));
    uint32_t elem_strideC = (uint32_t)(strideC / sizeof(uint16_t));
    uint32_t elem_strideD = (uint32_t)(strideD / sizeof(uint16_t));

    return vkblas_gemm_common(context, cmd, transA, transB,
                              m, n, k, VKBLAS_DTYPE_F16,
                              (const void*)alpha, A, lda, B, ldb,
                              (const void*)beta, C, ldc, D, ldd,
                              elem_strideA, elem_strideB,
                              elem_strideC, elem_strideD,
                              batchCount, VK_TRUE);
}

VkResult vkblas_bgemm(VkBLASContext* context, VkCommandBuffer cmd,
                      VkBLASOperation_t transA, VkBLASOperation_t transB,
                      int32_t m, int32_t n, int32_t k, const uint16_t* alpha,
                      VkBuffer A, int32_t lda, VkBuffer B, int32_t ldb,
                      const uint16_t* beta, VkBuffer C, int32_t ldc,
                      VkBuffer D, int32_t ldd) {
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;

    return vkblas_gemm_common(context, cmd, transA, transB,
                              m, n, k, VKBLAS_DTYPE_BF16,
                              (const void*)alpha, A, lda, B, ldb,
                              (const void*)beta, C, ldc, D, ldd,
                              0, 0, 0, 0, 1, VK_FALSE);
}

VkResult vkblas_bgemm_strided_batched(VkBLASContext* context, VkCommandBuffer cmd,
                                      VkBLASOperation_t transA, VkBLASOperation_t transB,
                                      int32_t m, int32_t n, int32_t k, const uint16_t* alpha,
                                      VkBuffer A, int32_t lda, int64_t strideA,
                                      VkBuffer B, int32_t ldb, int64_t strideB,
                                      const uint16_t* beta, VkBuffer C, int32_t ldc, int64_t strideC,
                                      VkBuffer D, int32_t ldd, int64_t strideD, int32_t batchCount) {
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0 || batchCount <= 0)
        return VK_SUCCESS;

    uint32_t elem_strideA = (uint32_t)(strideA / sizeof(uint16_t));
    uint32_t elem_strideB = (uint32_t)(strideB / sizeof(uint16_t));
    uint32_t elem_strideC = (uint32_t)(strideC / sizeof(uint16_t));
    uint32_t elem_strideD = (uint32_t)(strideD / sizeof(uint16_t));

    return vkblas_gemm_common(context, cmd, transA, transB,
                              m, n, k, VKBLAS_DTYPE_BF16,
                              (const void*)alpha, A, lda, B, ldb,
                              (const void*)beta, C, ldc, D, ldd,
                              elem_strideA, elem_strideB,
                              elem_strideC, elem_strideD,
                              batchCount, VK_TRUE);
}

/* Map a gemm_ex compute type to a storage dtype + element size.
   Supported: 32F -> f32 storage, 16F -> f16 storage (accumulated in f32 by
   the hgemm shader), 16B -> bf16 storage (accumulated in f32 by the bgemm
   shader). Anything else returns FEATURE_NOT_PRESENT. */
static VkResult vkblas_gemm_ex_dtype(VkBLASComputeType_t computeType,
                                     uint32_t* out_dtype, size_t* out_elem)
{
    switch (computeType) {
    case VKBLAS_COMPUTE_32F:
        *out_dtype = VKBLAS_DTYPE_F32;
        *out_elem   = sizeof(float);
        return VK_SUCCESS;
    case VKBLAS_COMPUTE_16F:
        /* f16 storage with f32 accumulation */
        *out_dtype = VKBLAS_DTYPE_F16;
        *out_elem   = sizeof(uint16_t);
        return VK_SUCCESS;
    case VKBLAS_COMPUTE_16B:
        /* bf16 storage (2-byte uint16) with f32 accumulation; reuses the
           bgemm shader path. The stride arithmetic in vkblas_gemm_ex divides
           byte strides by out_elem, which is correct for the 2-byte layout. */
        *out_dtype = VKBLAS_DTYPE_BF16;
        *out_elem   = sizeof(uint16_t);
        return VK_SUCCESS;
    default:
        return VK_ERROR_FEATURE_NOT_PRESENT;
    }
}

VkResult vkblas_gemm_ex(VkBLASContext* context, VkCommandBuffer cmd,
                        VkBLASOperation_t transA, VkBLASOperation_t transB,
                        int32_t m, int32_t n, int32_t k, const void* alpha,
                        VkBuffer A, int32_t lda, size_t strideA_element,
                        VkBuffer B, int32_t ldb, size_t strideB_element,
                        const void* beta, VkBuffer C, int32_t ldc, size_t strideC_element,
                        VkBuffer D, int32_t ldd, size_t strideD_element,
                        VkBLASComputeType_t computeType, VkBLASGemmFlags_t flags) {
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;
    (void)flags;

    uint32_t dtype = 0;
    size_t elem = 0;
    VkResult r = vkblas_gemm_ex_dtype(computeType, &dtype, &elem);
    if (r != VK_SUCCESS)
        return r;

    /* strideX_element is the byte stride between elements; 0 = tightly packed.
       Any other non-identity element stride is unsupported. */
    if ((strideA_element != 0 && strideA_element != elem) ||
        (strideB_element != 0 && strideB_element != elem) ||
        (strideC_element != 0 && strideC_element != elem) ||
        (strideD_element != 0 && strideD_element != elem))
        return VK_ERROR_INITIALIZATION_FAILED;

    return vkblas_gemm_common(context, cmd, transA, transB,
                              m, n, k, dtype,
                              alpha, A, lda, B, ldb, beta, C, ldc, D, ldd,
                              0, 0, 0, 0, 1, VK_FALSE);
}

VkResult vkblas_gemm_ex_strided_batched(VkBLASContext* context, VkCommandBuffer cmd,
                                        VkBLASOperation_t transA, VkBLASOperation_t transB,
                                        int32_t m, int32_t n, int32_t k, const void* alpha,
                                        VkBuffer A, int32_t lda, int64_t strideA, size_t strideA_element,
                                        VkBuffer B, int32_t ldb, int64_t strideB, size_t strideB_element,
                                        const void* beta, VkBuffer C, int32_t ldc, int64_t strideC, size_t strideC_element,
                                        VkBuffer D, int32_t ldd, int64_t strideD, size_t strideD_element,
                                        int32_t batchCount, VkBLASComputeType_t computeType, VkBLASGemmFlags_t flags) {
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0 || batchCount <= 0)
        return VK_SUCCESS;
    (void)flags;

    uint32_t dtype = 0;
    size_t elem = 0;
    VkResult r = vkblas_gemm_ex_dtype(computeType, &dtype, &elem);
    if (r != VK_SUCCESS)
        return r;

    /* strideX is bytes between matrices; strideX_element is the element byte
       stride (0 = tightly packed). Convert to element strides for the shader. */
    uint32_t elem_strideA = (uint32_t)(strideA / (int64_t)(strideA_element ? strideA_element : elem));
    uint32_t elem_strideB = (uint32_t)(strideB / (int64_t)(strideB_element ? strideB_element : elem));
    uint32_t elem_strideC = (uint32_t)(strideC / (int64_t)(strideC_element ? strideC_element : elem));
    uint32_t elem_strideD = (uint32_t)(strideD / (int64_t)(strideD_element ? strideD_element : elem));

    return vkblas_gemm_common(context, cmd, transA, transB,
                              m, n, k, dtype,
                              alpha, A, lda, B, ldb, beta, C, ldc, D, ldd,
                              elem_strideA, elem_strideB,
                              elem_strideC, elem_strideD,
                              batchCount, VK_TRUE);
}

/* ══════════════════════════════════════════════════════════════════════════ *
 * Fused quantized GEMM — dequant-in-matmul (Q8_0 / Q4_K / Q4_0 / Q5_K /
 * Q6_K / Q3_K / IQ4_XS weights)
 * ══════════════════════════════════════════════════════════════════════════ */

/* Resolve the dequant-in-matmul pipeline for a quantized weight format.
   Mirrors vkblas_ensure_pipeline: the qgemm kernels only exist at the
   baseline tier, so the fallback walk lands there regardless of the active
   tier. The distinct VKBLAS_DTYPE_QGEMM_* codes keep the cache keys separate
   from every plain GEMM. */
static VkResult vkblas_qgemm_ensure_pipeline(VkBLASContext* ctx,
                                             uint32_t kernel,
                                             VkPipeline* out_pipeline)
{
    /* Only the fused kernels have pipelines; anything else fails. */
    uint32_t dtype;
    switch (kernel) {
    case VKBLAS_DTYPE_QGEMM_Q8_0:
        dtype = VKBLAS_DTYPE_QGEMM_Q8_0;
        break;
    case VKBLAS_DTYPE_QGEMM_Q4K:
        dtype = VKBLAS_DTYPE_QGEMM_Q4K;
        break;
    case VKBLAS_DTYPE_QGEMM_Q4_0:
        dtype = VKBLAS_DTYPE_QGEMM_Q4_0;
        break;
    case VKBLAS_DTYPE_QGEMM_Q5K:
        dtype = VKBLAS_DTYPE_QGEMM_Q5K;
        break;
    case VKBLAS_DTYPE_QGEMM_Q6K:
        dtype = VKBLAS_DTYPE_QGEMM_Q6K;
        break;
    case VKBLAS_DTYPE_QGEMM_Q3K:
        dtype = VKBLAS_DTYPE_QGEMM_Q3K;
        break;
    case VKBLAS_DTYPE_QGEMM_IQ4XS:
        dtype = VKBLAS_DTYPE_QGEMM_IQ4XS;
        break;
    default:
        return VK_ERROR_FEATURE_NOT_PRESENT;
    }
    return vkblas_ensure_pipeline(ctx, dtype, 0, 0, VK_FALSE, out_pipeline);
}

/* Shared dispatch for all fused quantized GEMMs.
 *
 * Layout contract (documented in vkblas.h):
 *   - Wq is the weight matrix (n rows x k cols) stored as quantized blocks,
 *     row-major per row: row r starts at byte offset r * ldw.
 *       Q8_0:   36 B/block of  32 elems (f32 d + 32 int8).
 *       Q4_0:   20 B/block of  32 elems (f32 d + 16 packed nibbles).
 *       Q4_K:  144 B/block of 256 elems (ggml).
 *       Q5_K:  176 B/block of 256 elems (ggml).
 *       Q6_K:  210 B/block of 256 elems (ggml).
 *       Q3_K:  110 B/block of 256 elems (ggml).
 *       IQ4_XS:136 B/block of 256 elems (ggml).
 *   - x is f32 (k x m), column-major; y is f32 (n x m), column-major.
 *
 * Descriptor binding mirrors the plain GEMM 4-binding layout:
 *   binding 0 = Wq (read), binding 1 = x (read), binding 2 = y (read for
 *   the beta term), binding 3 = y (write). y is both C and D because the
 *   API computes in place: y = alpha*(dequant(W)*x) + beta*y.
 *
 * Push constants reuse vkblas_push_constants_t; the shader names them as in
 * gemm_f32.comp (pc.m = weight rows, pc.n = activation cols, pc.k = depth),
 * so the host swaps m/n and maps ldw/ldx/ldy onto lda/ldb/ldc/ldd.
 */
static VkResult vkblas_qgemm_common(VkBLASContext* ctx,
                                    VkCommandBuffer cmd,
                                    int32_t m, int32_t n, int32_t k,
                                    uint32_t kernel,
                                    const float* alpha,
                                    VkBuffer Wq, int32_t ldw,
                                    VkBuffer x, int32_t ldx,
                                    const float* beta,
                                    VkBuffer y, int32_t ldy)
{
    /* Ensure pipeline exists */
    VkPipeline pipeline = VK_NULL_HANDLE;
    VkResult r = vkblas_qgemm_ensure_pipeline(ctx, kernel, &pipeline);
    if (r != VK_SUCCESS)
        return r;

    /* Allocate descriptor set */
    VkDescriptorSet ds;
    r = vkblas_alloc_descriptor_set(ctx, &ds);
    if (r != VK_SUCCESS)
        return r;

    /* Wq -> binding 0, x -> binding 1, y -> binding 2 (beta read) and
       binding 3 (write). The same buffer is both C and D: the API updates
       y in place. */
    vkblas_write_descriptor_set(ctx, ds, Wq, x, y, y);

    /* Bind pipeline and descriptor set */
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
                            ctx->pipeline_layout, 0, 1, &ds, 0, NULL);

    /* Push constants: shader sees pc.m = weight rows (= n), pc.n = act
       cols (= m), pc.k = depth; strides map ldw/ldx/ldy -> lda/ldb/ldc/ldd. */
    vkblas_push_constants_t pc = {0};
    pc.m = (uint32_t)n;
    pc.n = (uint32_t)m;
    pc.k = (uint32_t)k;
    pc.alpha = *alpha;
    pc.beta  = *beta;
    if (pc.beta == 0.0f)
        pc.beta_is_zero = 1;
    pc.lda = (uint32_t)ldw;
    pc.ldb = (uint32_t)ldx;
    pc.ldc = (uint32_t)ldy;
    pc.ldd = (uint32_t)ldy;
    pc.transA = 0;
    pc.transB = 0;
    vkblas_push_pc(cmd, ctx->pipeline_layout, &pc);

    /* Compute grid: one workgroup per TILE_M x TILE_N output block of the
       n x m result y. */
    uint32_t gridX = (uint32_t)((n + VKBLAS_TILE_M - 1) / VKBLAS_TILE_M);
    uint32_t gridY = (uint32_t)((m + VKBLAS_TILE_N - 1) / VKBLAS_TILE_N);

    vkCmdDispatch(cmd, gridX, gridY, 1);

    return VK_SUCCESS;
}

VkResult vkblas_qgemm_q8_0_f32(VkBLASContext* ctx, VkCommandBuffer cmd,
                               int32_t m, int32_t n, int32_t k,
                               const float* alpha, VkBuffer Wq, int32_t ldw,
                               VkBuffer x, int32_t ldx,
                               const float* beta, VkBuffer y, int32_t ldy)
{
    if (!ctx || !cmd || !Wq || !x || !y || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;  /* no-op for zero-size matrices */

    return vkblas_qgemm_common(ctx, cmd, m, n, k,
                               VKBLAS_DTYPE_QGEMM_Q8_0,
                               alpha, Wq, ldw, x, ldx, beta, y, ldy);
}

VkResult vkblas_qgemm_q4k_f32(VkBLASContext* ctx, VkCommandBuffer cmd,
                              int32_t m, int32_t n, int32_t k,
                              const float* alpha, VkBuffer Wq, int32_t ldw,
                              VkBuffer x, int32_t ldx,
                              const float* beta, VkBuffer y, int32_t ldy)
{
    if (!ctx || !cmd || !Wq || !x || !y || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;  /* no-op for zero-size matrices */

    return vkblas_qgemm_common(ctx, cmd, m, n, k,
                               VKBLAS_DTYPE_QGEMM_Q4K,
                               alpha, Wq, ldw, x, ldx, beta, y, ldy);
}

VkResult vkblas_qgemm_q4_0_f32(VkBLASContext* ctx, VkCommandBuffer cmd,
                               int32_t m, int32_t n, int32_t k,
                               const float* alpha, VkBuffer Wq, int32_t ldw,
                               VkBuffer x, int32_t ldx,
                               const float* beta, VkBuffer y, int32_t ldy)
{
    if (!ctx || !cmd || !Wq || !x || !y || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;  /* no-op for zero-size matrices */

    return vkblas_qgemm_common(ctx, cmd, m, n, k,
                               VKBLAS_DTYPE_QGEMM_Q4_0,
                               alpha, Wq, ldw, x, ldx, beta, y, ldy);
}

VkResult vkblas_qgemm_q5k_f32(VkBLASContext* ctx, VkCommandBuffer cmd,
                              int32_t m, int32_t n, int32_t k,
                              const float* alpha, VkBuffer Wq, int32_t ldw,
                              VkBuffer x, int32_t ldx,
                              const float* beta, VkBuffer y, int32_t ldy)
{
    if (!ctx || !cmd || !Wq || !x || !y || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;  /* no-op for zero-size matrices */

    return vkblas_qgemm_common(ctx, cmd, m, n, k,
                               VKBLAS_DTYPE_QGEMM_Q5K,
                               alpha, Wq, ldw, x, ldx, beta, y, ldy);
}

VkResult vkblas_qgemm_q6k_f32(VkBLASContext* ctx, VkCommandBuffer cmd,
                              int32_t m, int32_t n, int32_t k,
                              const float* alpha, VkBuffer Wq, int32_t ldw,
                              VkBuffer x, int32_t ldx,
                              const float* beta, VkBuffer y, int32_t ldy)
{
    if (!ctx || !cmd || !Wq || !x || !y || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;  /* no-op for zero-size matrices */

    return vkblas_qgemm_common(ctx, cmd, m, n, k,
                               VKBLAS_DTYPE_QGEMM_Q6K,
                               alpha, Wq, ldw, x, ldx, beta, y, ldy);
}

VkResult vkblas_qgemm_q3k_f32(VkBLASContext* ctx, VkCommandBuffer cmd,
                              int32_t m, int32_t n, int32_t k,
                              const float* alpha, VkBuffer Wq, int32_t ldw,
                              VkBuffer x, int32_t ldx,
                              const float* beta, VkBuffer y, int32_t ldy)
{
    if (!ctx || !cmd || !Wq || !x || !y || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;  /* no-op for zero-size matrices */

    return vkblas_qgemm_common(ctx, cmd, m, n, k,
                               VKBLAS_DTYPE_QGEMM_Q3K,
                               alpha, Wq, ldw, x, ldx, beta, y, ldy);
}

VkResult vkblas_qgemm_iq4xs_f32(VkBLASContext* ctx, VkCommandBuffer cmd,
                                int32_t m, int32_t n, int32_t k,
                                const float* alpha, VkBuffer Wq, int32_t ldw,
                                VkBuffer x, int32_t ldx,
                                const float* beta, VkBuffer y, int32_t ldy)
{
    if (!ctx || !cmd || !Wq || !x || !y || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;  /* no-op for zero-size matrices */

    return vkblas_qgemm_common(ctx, cmd, m, n, k,
                               VKBLAS_DTYPE_QGEMM_IQ4XS,
                               alpha, Wq, ldw, x, ldx, beta, y, ldy);
}
