<#`
.SYNOPSIS
  Compiles GLSL compute shaders to SPIR-V and generates C headers with embedded blobs.

.DESCRIPTION
  Runs glslangValidator for each .comp file under shaders/vkblas/{baseline,subgroup,coopmatrix}/
  and shaders/vkmath/{baseline,subgroup/} and emits shaders_spv.h headers containing
  uint32_t arrays ready for #include.

  CMake shader list must match this script (per root AGENTS.md).
`#>

$VulkanSDK = if ($env:VULKAN_SDK) { $env:VULKAN_SDK } else { "C:\VulkanSDK\1.4.357.0" }
$glslang = Join-Path $VulkanSDK "Bin\glslangValidator.exe"
if (-not (Test-Path $glslang)) {
    $glslang = "glslangValidator"
}

$SpvDir = "shaders/spv"
if (-not (Test-Path $SpvDir)) { New-Item -ItemType Directory -Path $SpvDir | Out-Null }

$AnyFailed = $false

function Compile-Shaders {
    param(
        [string]$LibName,
        [string]$HeaderPath,
        [string[]]$ShaderDirs,
        [string[]]$DataTypes,
        [string[]]$Kernels
    )

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("// Auto-generated by compile_shaders.ps1 - DO NOT EDIT")
    [void]$sb.AppendLine("#ifndef ${LibName}_SHADERS_SPV_H")
    [void]$sb.AppendLine("#define ${LibName}_SHADERS_SPV_H")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("#include <stdint.h>")
    [void]$sb.AppendLine("#include <stddef.h>")
    [void]$sb.AppendLine("")

    foreach ($dir in $ShaderDirs) {
        foreach ($kernel in $Kernels) {
            foreach ($dt in $DataTypes) {
                $compFile = "shaders/${LibName}/$dir/${kernel}_${dt}.comp"
                if (-not (Test-Path $compFile)) { continue }

                $spvFile = Join-Path $SpvDir "$dir.$kernel.$dt.spv"

                $args = @(
                    "-V",
                    "--target-env", "vulkan1.4",
                    "-e", "main",
                    "-o", $spvFile,
                    $compFile
                )

                Write-Host "Compiling: $compFile -> $spvFile"
                $proc = Start-Process -FilePath $glslang -ArgumentList $args -Wait -NoNewWindow -PassThru -RedirectStandardError "$spvFile.err"
                if ($proc.ExitCode -ne 0) {
                    $err = Get-Content "$spvFile.err" -Raw
                    Write-Error "glslangValidator failed for $compFile`:`n$err"
                    $AnyFailed = $true
                    continue
                }

                $bytes = [System.IO.File]::ReadAllBytes($spvFile)
                $words = @()
                for ($i = 0; $i -lt $bytes.Length; $i += 4) {
                    # Cast each byte to [uint32] BEFORE shifting: PowerShell -shl
                    # on a Byte operand returns a Byte, so unshifted high bytes
                    # would silently truncate to 0.
                    $val = ([uint32]$bytes[$i]) -bor
                        (([uint32]$bytes[$i + 1]) -shl 8) -bor
                        (([uint32]$bytes[$i + 2]) -shl 16) -bor
                        (([uint32]$bytes[$i + 3]) -shl 24)
                    $words += $val
                }
                $arrName = "${LibName}_spv_${dir}_${kernel}_${dt}"
                $wc = $words.Length
                [void]$sb.AppendLine("// ${dir}_${kernel}_${dt} ($wc words)")
                [void]$sb.AppendLine("static const uint32_t ${arrName}[] = {")
                for ($i = 0; $i -lt $words.Length; $i++) {
                    if (($i % 8) -eq 0) { [void]$sb.AppendLine("    ") }
                    [void]$sb.Append("0x{0:X8}, " -f $words[$i])
                }
                [void]$sb.AppendLine("};")
                [void]$sb.AppendLine("static const size_t ${arrName}_size = sizeof(${arrName});")
                [void]$sb.AppendLine("")
            }
        }
    }

    [void]$sb.AppendLine("#endif /* ${LibName}_SHADERS_SPV_H */")
    [System.IO.File]::WriteAllText($HeaderPath, $sb.ToString())
    Write-Host "Generated: $HeaderPath"
}

# VKBLAS shaders
$VKBlasDirs = @("baseline", "subgroup", "coopmatrix")
$VKBlasDTs  = @("f32", "f16", "bf16", "i8")
$VKBlasKernels = @("gemm")
Compile-Shaders "vkblas" "src/vkblas/shaders_spv.h" $VKBlasDirs $VKBlasDTs $VKBlasKernels

# VKMath shaders
$VKMathDirs = @("baseline", "subgroup", "coopmatrix")
$VKMathDTs  = @("f32", "f16")
$VKMathKernels = @(
    "relu", "silu", "gelu", "tanh", "sigmoid",
    "add", "mul", "add_mul", "scale",
    "max_reduce_dim", "sum_reduce_dim"
)
Compile-Shaders "vkmath" "src/vkmath/shaders_spv.h" $VKMathDirs $VKMathDTs $VKMathKernels

if ($AnyFailed) {
    Write-Warning "Some shaders failed to compile."
    exit 1
}
