<#`
.SYNOPSIS
  Compiles GLSL compute shaders to SPIR-V and generates C headers with embedded blobs.

.DESCRIPTION
  Auto-discovers every library under shaders/<lib>/<tier>/. Each *.comp file
  becomes <lib>_spv_<tier>_<kernel>_<dtype>[] in src/<lib>/shaders_spv.h.

  Adding a new library is a zero-script-change operation: drop .comp files
  under shaders/<lib>/{baseline,subgroup,coopmatrix}/ and this script emits
  src/<lib>/shaders_spv.h with uint32_t arrays ready for #include.

  CMake shader list must match this script (per root AGENTS.md).
`#>

$VulkanSDK = if ($env:VULKAN_SDK) { $env:VULKAN_SDK } else { "C:\VulkanSDK\1.4.357.0" }
$glslang = Join-Path $VulkanSDK "Bin\glslangValidator.exe"
if (-not (Test-Path $glslang)) {
    $glslang = "glslangValidator"
}

$SpvDir = "shaders/spv"
if (-not (Test-Path $SpvDir)) { New-Item -ItemType Directory -Path $SpvDir | Out-Null }

$AnyFailed = $false

function Compile-Library {
    param([string]$LibName)

    $HeaderPath = "src/${LibName}/shaders_spv.h"
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("// Auto-generated by compile_shaders.ps1 - DO NOT EDIT")
    [void]$sb.AppendLine("#ifndef ${LibName}_SHADERS_SPV_H")
    [void]$sb.AppendLine("#define ${LibName}_SHADERS_SPV_H")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("#include <stdint.h>")
    [void]$sb.AppendLine("#include <stddef.h>")
    [void]$sb.AppendLine("")

    $libDir = "shaders/${LibName}"
    $tiers = Get-ChildItem $libDir -Directory -ErrorAction SilentlyContinue
    $anyComp = $false
    foreach ($tier in $tiers) {
        $tierName = $tier.Name
        foreach ($comp in (Get-ChildItem $tier.FullName -Filter "*.comp")) {
            $anyComp = $true
            $name = $comp.BaseName   # e.g. "relu_f32"
            $spvFile = Join-Path $SpvDir "$tierName.$name.spv"

            $args = @(
                "-V",
                "--target-env", "vulkan1.4",
                "-e", "main",
                "-o", $spvFile,
                $comp.FullName
            )

            Write-Host "Compiling: $($comp.FullName) -> $spvFile"
            $proc = Start-Process -FilePath $glslang -ArgumentList $args -Wait -NoNewWindow -PassThru -RedirectStandardError "$spvFile.err"
            if ($proc.ExitCode -ne 0) {
                $err = Get-Content "$spvFile.err" -Raw
                Write-Error "glslangValidator failed for $($comp.FullName)`:`n$err"
                $AnyFailed = $true
                continue
            }

            $bytes = [System.IO.File]::ReadAllBytes($spvFile)
            $words = @()
            for ($i = 0; $i -lt $bytes.Length; $i += 4) {
                # Cast each byte to [uint32] BEFORE shifting: PowerShell -shl
                # on a Byte operand returns a Byte, so unshifted high bytes
                # would silently truncate to 0.
                $val = ([uint32]$bytes[$i]) -bor
                    (([uint32]$bytes[$i + 1]) -shl 8) -bor
                    (([uint32]$bytes[$i + 2]) -shl 16) -bor
                    (([uint32]$bytes[$i + 3]) -shl 24)
                $words += $val
            }
            $arrName = "${LibName}_spv_${tierName}_${name}"
            $wc = $words.Length
            [void]$sb.AppendLine("// ${tierName}_${name} ($wc words)")
            [void]$sb.AppendLine("static const uint32_t ${arrName}[] = {")
            for ($i = 0; $i -lt $words.Length; $i++) {
                if (($i % 8) -eq 0) { [void]$sb.AppendLine("    ") }
                [void]$sb.Append("0x{0:X8}, " -f $words[$i])
            }
            [void]$sb.AppendLine("};")
            [void]$sb.AppendLine("#define ${arrName}_size (sizeof(${arrName}))")
            [void]$sb.AppendLine("")
        }
    }

    [void]$sb.AppendLine("#endif /* ${LibName}_SHADERS_SPV_H */")
    if ($anyComp) {
        # Ensure the target src/<lib> directory exists before writing.
        $headerDir = Split-Path $HeaderPath
        if (-not (Test-Path $headerDir)) { New-Item -ItemType Directory -Path $headerDir -Force | Out-Null }
        [System.IO.File]::WriteAllText($HeaderPath, $sb.ToString())
        Write-Host "Generated: $HeaderPath"
    }
}

# Auto-discover every library under shaders/ (skip the spv intermediate dir).
$libs = Get-ChildItem "shaders" -Directory | Where-Object { $_.Name -ne "spv" }
foreach ($lib in $libs) {
    Compile-Library $lib.Name
}

if ($AnyFailed) {
    Write-Warning "Some shaders failed to compile."
    exit 1
}
