<#`
.SYNOPSIS
  Compiles GLSL compute shaders to SPIR-V and generates a C header with embedded blobs.

.DESCRIPTION
  Runs glslangValidator for each .comp file under shaders/vkblas/{baseline,subgroup,coopmatrix}/
  and emits shaders_spv.h containing uint32_t arrays ready for #include.
`#>

$VulkanSDK = if ($env:VULKAN_SDK) { $env:VULKAN_SDK } else { "C:\VulkanSDK\1.4.357.0" }
$glslang = Join-Path $VulkanSDK "Bin\glslangValidator.exe"
if (-not (Test-Path $glslang)) {
    $glslang = "glslangValidator"
}

$ShaderDirs = @("baseline", "subgroup", "coopmatrix")
$DataTypes  = @("f32", "f16", "bf16", "i8")  # add more as shaders are written
$Kernels   = @("gemm")

$SpvDir = "shaders/spv"
if (-not (Test-Path $SpvDir)) { New-Item -ItemType Directory -Path $SpvDir | Out-Null }

$HeaderPath = "src/vkblas/shaders_spv.h"
$sb = New-Object System.Text.StringBuilder
$sb.AppendLine("// Auto-generated by compile_shaders.ps1 — DO NOT EDIT") | Out-Null
$sb.AppendLine("#ifndef VKBLAS_SHADERS_SPV_H") | Out-Null
$sb.AppendLine("#define VKBLAS_SHADERS_SPV_H") | Out-Null
$sb.AppendLine("") | Out-Null

$AnyFailed = $false

foreach ($dir in $ShaderDirs) {
    foreach ($kernel in $Kernels) {
        foreach ($dt in $DataTypes) {
            $compFile = "shaders/vkblas/$dir/${kernel}_${dt}.comp"
            if (-not (Test-Path $compFile)) { continue }

            $spvFile = Join-Path $SpvDir "$dir.$kernel.$dt.spv"

            # Compile: use Vulkan 1.4 target with int64 + subgroup extensions
            $args = @(
                "-V",                          # Vulkan SPIR-V
                "--target-env", "vulkan1.4",
                "-e", "main",                  # entry point
                "-o", $spvFile,
                $compFile
            )

            Write-Host "Compiling: $compFile -> $spvFile"
            $proc = Start-Process -FilePath $glslang -ArgumentList $args -Wait -NoNewWindow -PassThru -RedirectStandardError "$spvFile.err"
            if ($proc.ExitCode -ne 0) {
                $err = Get-Content "$spvFile.err" -Raw
                Write-Error "glslangValidator failed for $compFile`:`n$err"
                $AnyFailed = $true
                continue
            }

            # Convert SPIR-V binary to C uint32_t array
            $bytes = [System.IO.File]::ReadAllBytes($spvFile)
            $words = @()
            for ($i = 0; $i -lt $bytes.Length; $i += 4) {
                $val = [uint32]($bytes[$i] -bor
                    ($bytes[$i + 1] -shl 8) -bor
                    ($bytes[$i + 2] -shl 16) -bor
                    ($bytes[$i + 3] -shl 24))
                $words += $val
            }
            $arrName = "vkblas_spv_${dir}_${kernel}_${dt}"
            $sb.AppendLine("static const uint32_t ${arrName}[] = {") | Out-Null
            $sb.AppendLine("    0x" + "{0:X8}" -f $words[0]) | Out-Null
            for ($i = 1; $i -lt $words.Length; $i++) {
                if (($i % 8) -eq 0) { $sb.AppendLine() | Out-Null }
                $sb.Append("0x{0:X8}, " -f $words[$i]) | Out-Null
            }
            $sb.AppendLine("};") | Out-Null
            $sb.AppendLine("static const size_t ${arrName}_size = sizeof(${arrName});") | Out-Null
            $sb.AppendLine("") | Out-Null
        }
    }
}

$sb.AppendLine("#endif /* VKBLAS_SHADERS_SPV_H */") | Out-Null
[System.IO.File]::WriteAllText($HeaderPath, $sb.ToString())
Write-Host "Generated: $Header"

if ($AnyFailed) {
    Write-Warning "Some shaders failed to compile."
    exit 1
}
