# CMake generated Testfile for 
# Source directory: C:/vaist
# Build directory: C:/vaist/bi2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_core_test]=] "C:/vaist/bi2/Debug/vaist_cpp_core_test.exe")
  set_tests_properties([=[vaist_cpp_core_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_core_test]=] "C:/vaist/bi2/Release/vaist_cpp_core_test.exe")
  set_tests_properties([=[vaist_cpp_core_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_core_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_core_test.exe")
  set_tests_properties([=[vaist_cpp_core_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_core_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_core_test.exe")
  set_tests_properties([=[vaist_cpp_core_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_core_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_runtime_test]=] "C:/vaist/bi2/Debug/vaist_cpp_runtime_test.exe")
  set_tests_properties([=[vaist_cpp_runtime_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_runtime_test]=] "C:/vaist/bi2/Release/vaist_cpp_runtime_test.exe")
  set_tests_properties([=[vaist_cpp_runtime_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_runtime_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_runtime_test.exe")
  set_tests_properties([=[vaist_cpp_runtime_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_runtime_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_runtime_test.exe")
  set_tests_properties([=[vaist_cpp_runtime_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_runtime_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_tensor_test]=] "C:/vaist/bi2/Debug/vaist_cpp_tensor_test.exe")
  set_tests_properties([=[vaist_cpp_tensor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_tensor_test]=] "C:/vaist/bi2/Release/vaist_cpp_tensor_test.exe")
  set_tests_properties([=[vaist_cpp_tensor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_tensor_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_tensor_test.exe")
  set_tests_properties([=[vaist_cpp_tensor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_tensor_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_tensor_test.exe")
  set_tests_properties([=[vaist_cpp_tensor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_tensor_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_compute_test]=] "C:/vaist/bi2/Debug/vaist_cpp_compute_test.exe")
  set_tests_properties([=[vaist_cpp_compute_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_compute_test]=] "C:/vaist/bi2/Release/vaist_cpp_compute_test.exe")
  set_tests_properties([=[vaist_cpp_compute_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_compute_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_compute_test.exe")
  set_tests_properties([=[vaist_cpp_compute_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_compute_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_compute_test.exe")
  set_tests_properties([=[vaist_cpp_compute_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_compute_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_quant_test]=] "C:/vaist/bi2/Debug/vaist_cpp_quant_test.exe")
  set_tests_properties([=[vaist_cpp_quant_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_quant_test]=] "C:/vaist/bi2/Release/vaist_cpp_quant_test.exe")
  set_tests_properties([=[vaist_cpp_quant_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_quant_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_quant_test.exe")
  set_tests_properties([=[vaist_cpp_quant_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_quant_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_quant_test.exe")
  set_tests_properties([=[vaist_cpp_quant_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_quant_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_graph_test]=] "C:/vaist/bi2/Debug/vaist_cpp_graph_test.exe")
  set_tests_properties([=[vaist_cpp_graph_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_graph_test]=] "C:/vaist/bi2/Release/vaist_cpp_graph_test.exe")
  set_tests_properties([=[vaist_cpp_graph_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_graph_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_graph_test.exe")
  set_tests_properties([=[vaist_cpp_graph_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_graph_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_graph_test.exe")
  set_tests_properties([=[vaist_cpp_graph_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_graph_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_model_test]=] "C:/vaist/bi2/Debug/vaist_cpp_model_test.exe")
  set_tests_properties([=[vaist_cpp_model_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_model_test]=] "C:/vaist/bi2/Release/vaist_cpp_model_test.exe")
  set_tests_properties([=[vaist_cpp_model_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_model_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_model_test.exe")
  set_tests_properties([=[vaist_cpp_model_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_model_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_model_test.exe")
  set_tests_properties([=[vaist_cpp_model_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_model_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_nn_test]=] "C:/vaist/bi2/Debug/vaist_cpp_nn_test.exe")
  set_tests_properties([=[vaist_cpp_nn_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_nn_test]=] "C:/vaist/bi2/Release/vaist_cpp_nn_test.exe")
  set_tests_properties([=[vaist_cpp_nn_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_nn_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_nn_test.exe")
  set_tests_properties([=[vaist_cpp_nn_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_nn_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_nn_test.exe")
  set_tests_properties([=[vaist_cpp_nn_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_nn_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_llm_test]=] "C:/vaist/bi2/Debug/vaist_cpp_llm_test.exe")
  set_tests_properties([=[vaist_cpp_llm_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_llm_test]=] "C:/vaist/bi2/Release/vaist_cpp_llm_test.exe")
  set_tests_properties([=[vaist_cpp_llm_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_llm_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_llm_test.exe")
  set_tests_properties([=[vaist_cpp_llm_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_llm_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_llm_test.exe")
  set_tests_properties([=[vaist_cpp_llm_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_llm_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_engine_test]=] "C:/vaist/bi2/Debug/vaist_cpp_engine_test.exe")
  set_tests_properties([=[vaist_cpp_engine_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_engine_test]=] "C:/vaist/bi2/Release/vaist_cpp_engine_test.exe")
  set_tests_properties([=[vaist_cpp_engine_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_engine_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_engine_test.exe")
  set_tests_properties([=[vaist_cpp_engine_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_engine_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_engine_test.exe")
  set_tests_properties([=[vaist_cpp_engine_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_engine_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_ai_test]=] "C:/vaist/bi2/Debug/vaist_cpp_ai_test.exe")
  set_tests_properties([=[vaist_cpp_ai_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_ai_test]=] "C:/vaist/bi2/Release/vaist_cpp_ai_test.exe")
  set_tests_properties([=[vaist_cpp_ai_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_ai_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_ai_test.exe")
  set_tests_properties([=[vaist_cpp_ai_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_ai_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_ai_test.exe")
  set_tests_properties([=[vaist_cpp_ai_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_ai_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_distributed_test]=] "C:/vaist/bi2/Debug/vaist_cpp_distributed_test.exe")
  set_tests_properties([=[vaist_cpp_distributed_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_distributed_test]=] "C:/vaist/bi2/Release/vaist_cpp_distributed_test.exe")
  set_tests_properties([=[vaist_cpp_distributed_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_distributed_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_distributed_test.exe")
  set_tests_properties([=[vaist_cpp_distributed_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_distributed_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_distributed_test.exe")
  set_tests_properties([=[vaist_cpp_distributed_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_distributed_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_blas_test]=] "C:/vaist/bi2/Debug/vaist_cpp_blas_test.exe")
  set_tests_properties([=[vaist_cpp_blas_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_blas_test]=] "C:/vaist/bi2/Release/vaist_cpp_blas_test.exe")
  set_tests_properties([=[vaist_cpp_blas_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_blas_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_blas_test.exe")
  set_tests_properties([=[vaist_cpp_blas_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_blas_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_blas_test.exe")
  set_tests_properties([=[vaist_cpp_blas_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_blas_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_linalg_test]=] "C:/vaist/bi2/Debug/vaist_cpp_linalg_test.exe")
  set_tests_properties([=[vaist_cpp_linalg_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_linalg_test]=] "C:/vaist/bi2/Release/vaist_cpp_linalg_test.exe")
  set_tests_properties([=[vaist_cpp_linalg_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_linalg_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_linalg_test.exe")
  set_tests_properties([=[vaist_cpp_linalg_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_linalg_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_linalg_test.exe")
  set_tests_properties([=[vaist_cpp_linalg_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_linalg_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_cpp_attn_test]=] "C:/vaist/bi2/Debug/vaist_cpp_attn_test.exe")
  set_tests_properties([=[vaist_cpp_attn_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_cpp_attn_test]=] "C:/vaist/bi2/Release/vaist_cpp_attn_test.exe")
  set_tests_properties([=[vaist_cpp_attn_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_cpp_attn_test]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_attn_test.exe")
  set_tests_properties([=[vaist_cpp_attn_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_cpp_attn_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_attn_test.exe")
  set_tests_properties([=[vaist_cpp_attn_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;190;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_cpp_attn_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[stack_smoke]=] "C:/vaist/bi2/Debug/vaist_stack_smoke.exe")
  set_tests_properties([=[stack_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;337;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[stack_smoke]=] "C:/vaist/bi2/Release/vaist_stack_smoke.exe")
  set_tests_properties([=[stack_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;337;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[stack_smoke]=] "C:/vaist/bi2/MinSizeRel/vaist_stack_smoke.exe")
  set_tests_properties([=[stack_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;337;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[stack_smoke]=] "C:/vaist/bi2/RelWithDebInfo/vaist_stack_smoke.exe")
  set_tests_properties([=[stack_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;337;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[stack_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[linalg_test]=] "C:/vaist/bi2/Debug/vaist_linalg_test.exe")
  set_tests_properties([=[linalg_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;345;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[linalg_test]=] "C:/vaist/bi2/Release/vaist_linalg_test.exe")
  set_tests_properties([=[linalg_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;345;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[linalg_test]=] "C:/vaist/bi2/MinSizeRel/vaist_linalg_test.exe")
  set_tests_properties([=[linalg_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;345;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[linalg_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_linalg_test.exe")
  set_tests_properties([=[linalg_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;345;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[linalg_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[blas_test]=] "C:/vaist/bi2/Debug/vaist_blas_test.exe")
  set_tests_properties([=[blas_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;353;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[blas_test]=] "C:/vaist/bi2/Release/vaist_blas_test.exe")
  set_tests_properties([=[blas_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;353;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[blas_test]=] "C:/vaist/bi2/MinSizeRel/vaist_blas_test.exe")
  set_tests_properties([=[blas_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;353;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[blas_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_blas_test.exe")
  set_tests_properties([=[blas_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;353;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[blas_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[vaist_blas_vulkan_test]=] "C:/vaist/bi2/Debug/vaist_blas_vulkan_test.exe")
  set_tests_properties([=[vaist_blas_vulkan_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;364;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[vaist_blas_vulkan_test]=] "C:/vaist/bi2/Release/vaist_blas_vulkan_test.exe")
  set_tests_properties([=[vaist_blas_vulkan_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;364;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[vaist_blas_vulkan_test]=] "C:/vaist/bi2/MinSizeRel/vaist_blas_vulkan_test.exe")
  set_tests_properties([=[vaist_blas_vulkan_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;364;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[vaist_blas_vulkan_test]=] "C:/vaist/bi2/RelWithDebInfo/vaist_blas_vulkan_test.exe")
  set_tests_properties([=[vaist_blas_vulkan_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;364;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[vaist_blas_vulkan_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[cpp_smoke]=] "C:/vaist/bi2/Debug/vaist_cpp_smoke.exe")
  set_tests_properties([=[cpp_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;373;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[cpp_smoke]=] "C:/vaist/bi2/Release/vaist_cpp_smoke.exe")
  set_tests_properties([=[cpp_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;373;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[cpp_smoke]=] "C:/vaist/bi2/MinSizeRel/vaist_cpp_smoke.exe")
  set_tests_properties([=[cpp_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;373;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[cpp_smoke]=] "C:/vaist/bi2/RelWithDebInfo/vaist_cpp_smoke.exe")
  set_tests_properties([=[cpp_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;373;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[cpp_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[python_component_load]=] "C:/Program Files/Python312/python.exe" "C:/vaist/tests/python_components.py" "C:/vaist/bi2" "windows")
  set_tests_properties([=[python_component_load]=] PROPERTIES  ENVIRONMENT "PYTHONPATH=C:/vaist/vulkan/windows/python" _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;377;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[python_component_load]=] "C:/Program Files/Python312/python.exe" "C:/vaist/tests/python_components.py" "C:/vaist/bi2" "windows")
  set_tests_properties([=[python_component_load]=] PROPERTIES  ENVIRONMENT "PYTHONPATH=C:/vaist/vulkan/windows/python" _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;377;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[python_component_load]=] "C:/Program Files/Python312/python.exe" "C:/vaist/tests/python_components.py" "C:/vaist/bi2" "windows")
  set_tests_properties([=[python_component_load]=] PROPERTIES  ENVIRONMENT "PYTHONPATH=C:/vaist/vulkan/windows/python" _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;377;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[python_component_load]=] "C:/Program Files/Python312/python.exe" "C:/vaist/tests/python_components.py" "C:/vaist/bi2" "windows")
  set_tests_properties([=[python_component_load]=] PROPERTIES  ENVIRONMENT "PYTHONPATH=C:/vaist/vulkan/windows/python" _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;377;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[python_component_load]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[clean_staging_load]=] "C:/Program Files/Python312/python.exe" "C:/vaist/tests/clean_staging.py" "C:/vaist/bi2" "windows" "C:/Program Files/CMake/bin/cmake.exe")
  set_tests_properties([=[clean_staging_load]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;383;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[clean_staging_load]=] "C:/Program Files/Python312/python.exe" "C:/vaist/tests/clean_staging.py" "C:/vaist/bi2" "windows" "C:/Program Files/CMake/bin/cmake.exe")
  set_tests_properties([=[clean_staging_load]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;383;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[clean_staging_load]=] "C:/Program Files/Python312/python.exe" "C:/vaist/tests/clean_staging.py" "C:/vaist/bi2" "windows" "C:/Program Files/CMake/bin/cmake.exe")
  set_tests_properties([=[clean_staging_load]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;383;add_test;C:/vaist/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[clean_staging_load]=] "C:/Program Files/Python312/python.exe" "C:/vaist/tests/clean_staging.py" "C:/vaist/bi2" "windows" "C:/Program Files/CMake/bin/cmake.exe")
  set_tests_properties([=[clean_staging_load]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/vaist/CMakeLists.txt;383;add_test;C:/vaist/CMakeLists.txt;0;")
else()
  add_test([=[clean_staging_load]=] NOT_AVAILABLE)
endif()
