/**
 * \file vkblas.c
 * \brief Vulkan-native BLAS implementation.
 *
 * Implements context lifecycle, lazy pipeline creation with caching,
 * capability-based shader tier selection, and GEMM dispatch for f32
 * (sgemm, sgemm_strided_batched, sgemm_batched).
 */

#include "vkblas.h"
#include "vkblas_internal.h"
#include "shaders_spv.h"

#include <string.h>
#include <stdio.h>
#include <stdlib.h>

/* ── Specialization constant values ──────────────────────────────────────── */

#define VKBLAS_TILE_M 16
#define VKBLAS_TILE_N 16
#define VKBLAS_TILE_K 16

/* ── Specialization constant map (same for all f32 tiers) ────────────────── */

static VkSpecializationMapEntry vkblas_sc_map[] = {
    { 0, 0, sizeof(uint32_t) },   /* TILE_M */
    { 1, 4, sizeof(uint32_t) },   /* TILE_N */
    { 2, 8, sizeof(uint32_t) },   /* TILE_K */
    { 3, 12, sizeof(uint32_t) },  /* SG_WIDTH (subgroup) */
    { 4, 16, sizeof(uint32_t) },  /* CM_MSIZE (coopmatrix) */
    { 5, 20, sizeof(uint32_t) },  /* CM_NSIZE (coopmatrix) */
    { 6, 24, sizeof(uint32_t) },  /* CM_KSIZE (coopmatrix) */
};

/* ── Forward declarations for SPIR-V blobs ────────────────────────────────── */
/* Declared in shaders_spv.h — generated by compile_shaders.ps1 */

/* ── Hash function ───────────────────────────────────────────────────────── */

uint64_t vkblas_hash_key(uint32_t dt, uint32_t tA, uint32_t tB,
                         uint32_t strided, uint32_t tier)
{
    uint64_t h = (uint64_t)dt;
    h = h * 31 + tA;
    h = h * 31 + tB;
    h = h * 31 + strided;
    h = h * 31 + tier;
    h = h * 31 + VKBLAS_TILE_M;
    h = h * 31 + VKBLAS_TILE_N;
    h = h * 31 + VKBLAS_TILE_K;
    return h;
}

/* ── Shader blob selector ────────────────────────────────────────────────── */

static const uint32_t* vkblas_select_spirv(VkBLASContext* ctx,
                                           uint32_t data_type,
                                           VkBLASTier_t tier,
                                           size_t* out_size)
{
    (void)ctx;
    if (data_type != VKBLAS_DTYPE_F32) {
        /* Only f32 is implemented in this iteration */
        return NULL;
    }

    switch (tier) {
    case VKBLAS_TIER_COOPMATRIX:
        *out_size = vkblas_spv_coopmatrix_gemm_f32_size;
        return vkblas_spv_coopmatrix_gemm_f32;
    case VKBLAS_TIER_SUBGROUP:
        *out_size = vkblas_spv_subgroup_gemm_f32_size;
        return vkblas_spv_subgroup_gemm_f32;
    case VKBLAS_TIER_BASELINE:
        *out_size = vkblas_spv_baseline_gemm_f32_size;
        return vkblas_spv_baseline_gemm_f32;
    default:
        return NULL;
    }
}

/* ── Specialization constant data ─────────────────────────────────────────── */

static void vkblas_fill_sc_data(uint32_t* data, VkBLASTier_t tier)
{
    (void)tier;
    data[0] = VKBLAS_TILE_M;   /* constant_id 0 */
    data[1] = VKBLAS_TILE_N;   /* constant_id 1 */
    data[2] = VKBLAS_TILE_K;   /* constant_id 2 */
    data[3] = 32;              /* SG_WIDTH (constant_id 3) */
    data[4] = 16;              /* CM_MSIZE (constant_id 4) */
    data[5] = 16;              /* CM_NSIZE (constant_id 5) */
    data[6] = 16;              /* CM_KSIZE (constant_id 6) */
}

/* ── Pipeline layout ─────────────────────────────────────────────────────── */

VkPipelineLayout vkblas_get_pipeline_layout(VkBLASContext* ctx)
{
    return ctx->pipeline_layout;
}

/* ── Shader module ───────────────────────────────────────────────────────── */

VkResult vkblas_load_shader_module(VkDevice device,
                                   const uint32_t* spirv, size_t spirv_words,
                                   VkShaderModule* out_module)
{
    VkShaderModuleCreateInfo smci = {
        .sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        .pNext    = NULL,
        .flags    = 0,
        .codeSize = spirv_words,
        .pCode    = spirv,
    };
    return vkCreateShaderModule(device, &smci, NULL, out_module);
}

/* ── Descriptor set layout ────────────────────────────────────────────────── */

static VkResult vkblas_create_set_layout(VkBLASContext* ctx)
{
    VkDescriptorSetLayoutBinding bindings[4] = {
        { 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, NULL },
        { 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, NULL },
        { 2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, NULL },
        { 3, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, NULL },
    };

    VkDescriptorSetLayoutCreateInfo dslci = {
        .sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        .bindingCount = 4,
        .pBindings    = bindings,
    };
    return vkCreateDescriptorSetLayout(ctx->device, &dslci, NULL, &ctx->set_layout);
}

/* ── Pipeline layout ─────────────────────────────────────────────────────── */

static VkResult vkblas_create_pipeline_layout(VkBLASContext* ctx)
{
    VkPushConstantRange pcr = {
        .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
        .offset     = 0,
        .size       = sizeof(vkblas_push_constants_t),
    };

    VkPipelineLayoutCreateInfo plci = {
        .sType          = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
        .setLayoutCount = 1,
        .pSetLayouts    = &ctx->set_layout,
        .pushConstantRangeCount = 1,
        .pPushConstantRanges    = &pcr,
    };
    return vkCreatePipelineLayout(ctx->device, &plci, NULL, &ctx->pipeline_layout);
}

/* ── Descriptor pool ──────────────────────────────────────────────────────── */

static VkResult vkblas_create_descriptor_pool(VkBLASContext* ctx)
{
    VkDescriptorPoolSize pool_sizes[1] = {
        { VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, VKBLAS_MAX_PIPELINES },
    };

    VkDescriptorPoolCreateInfo dpci = {
        .sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
        .flags         = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT,
        .maxSets       = VKBLAS_MAX_PIPELINES,
        .poolSizeCount = 1,
        .pPoolSizes    = pool_sizes,
    };
    return vkCreateDescriptorPool(ctx->device, &dpci, NULL, &ctx->descriptor_pool);
}

/* ── Pipeline cache lookup / creation ─────────────────────────────────────── */

static uint32_t vkblas_hash_to_slot(uint64_t key)
{
    /* Simple multiplicative hash + modulo (power-of-two table) */
    key ^= key >> 32;
    key *= 0x9e3779b97f4a7c15ULL;
    return (uint32_t)(key & (VKBLAS_MAX_PIPELINES - 1));
}

VkPipeline vkblas_get_cached_pipeline(VkBLASContext* ctx,
                                       uint32_t data_type,
                                       VkBool32 transA, VkBool32 transB,
                                       VkBool32 is_strided)
{
    uint64_t key = vkblas_hash_key(data_type, transA, transB, is_strided,
                                   (uint32_t)ctx->active_tier);
    uint32_t slot = vkblas_hash_to_slot(key);

    for (uint32_t i = 0; i < VKBLAS_MAX_PIPELINES; ++i) {
        uint32_t idx = (slot + i) & (VKBLAS_MAX_PIPELINES - 1);
        if (!ctx->pipelines[idx].valid)
            break;
        if (ctx->pipelines[idx].key == key)
            return ctx->pipelines[idx].pipeline;
    }
    return VK_NULL_HANDLE;
}

VkResult vkblas_ensure_pipeline(VkBLASContext* ctx,
                                uint32_t data_type,
                                uint32_t transA, uint32_t transB,
                                uint32_t is_strided,
                                VkPipeline* out_pipeline)
{
    /* Try cache first */
    VkPipeline cached = vkblas_get_cached_pipeline(ctx, data_type,
                                                   transA, transB, is_strided);
    if (cached != VK_NULL_HANDLE) {
        *out_pipeline = cached;
        return VK_SUCCESS;
    }

    /* Select SPIR-V blob for the active tier */
    size_t spirv_size = 0;
    const uint32_t* spirv = vkblas_select_spirv(ctx, data_type, ctx->active_tier,
                                                 &spirv_size);
    if (spirv == NULL)
        return VK_ERROR_FEATURE_NOT_PRESENT;

    /* Create shader module */
    VkShaderModule sm;
    VkResult r = vkblas_load_shader_module(ctx->device, spirv, spirv_size, &sm);
    if (r != VK_SUCCESS)
        return r;

    /* Specialization constants */
    uint32_t sc_data[7];
    vkblas_fill_sc_data(sc_data, ctx->active_tier);

    VkSpecializationInfo si = {
        .mapEntryCount = 7,
        .pMapEntries   = vkblas_sc_map,
        .dataSize      = sizeof(sc_data),
        .pData         = sc_data,
    };

    VkComputePipelineCreateInfo cpci = {
        .sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
        .stage  = {
            .sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
            .stage  = VK_SHADER_STAGE_COMPUTE_BIT,
            .module = sm,
            .pName  = "main",
            .pSpecializationInfo = &si,
        },
        .layout = ctx->pipeline_layout,
    };

    VkPipeline pipeline;
    r = vkCreateComputePipelines(ctx->device, ctx->pipeline_cache, 1, &cpci,
                                  NULL, &pipeline);
    vkDestroyShaderModule(ctx->device, sm, NULL);
    if (r != VK_SUCCESS)
        return r;

    /* Insert into cache */
    uint64_t key = vkblas_hash_key(data_type, transA, transB, is_strided,
                                   (uint32_t)ctx->active_tier);
    uint32_t slot = vkblas_hash_to_slot(key);

    for (uint32_t i = 0; i < VKBLAS_MAX_PIPELINES; ++i) {
        uint32_t idx = (slot + i) & (VKBLAS_MAX_PIPELINES - 1);
        if (!ctx->pipelines[idx].valid) {
            ctx->pipelines[idx].key        = key;
            ctx->pipelines[idx].pipeline   = pipeline;
            ctx->pipelines[idx].layout     = ctx->pipeline_layout;
            ctx->pipelines[idx].data_type  = data_type;
            ctx->pipelines[idx].transA     = transA;
            ctx->pipelines[idx].transB     = transB;
            ctx->pipelines[idx].is_strided = is_strided;
            ctx->pipelines[idx].tier       = (uint32_t)ctx->active_tier;
            ctx->pipelines[idx].valid      = 1;
            ctx->pipeline_count++;
            break;
        }
    }

    *out_pipeline = pipeline;
    return VK_SUCCESS;
}

/* ── Descriptor set allocation ────────────────────────────────────────────── */

VkResult vkblas_alloc_descriptor_set(VkBLASContext* ctx, VkDescriptorSet* out)
{
    VkDescriptorSetAllocateInfo dsai = {
        .sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
        .descriptorPool     = ctx->descriptor_pool,
        .descriptorSetCount = 1,
        .pSetLayouts        = &ctx->set_layout,
    };
    return vkAllocateDescriptorSets(ctx->device, &dsai, out);
}

/* ── Descriptor set write ─────────────────────────────────────────────────── */

void vkblas_write_descriptor_set(VkBLASContext* ctx, VkDescriptorSet ds,
                                 VkBuffer A, VkBuffer B, VkBuffer C, VkBuffer D)
{
    VkDescriptorBufferInfo bi[4] = {
        { A, 0, VK_WHOLE_SIZE },
        { B, 0, VK_WHOLE_SIZE },
        { C, 0, VK_WHOLE_SIZE },
        { D, 0, VK_WHOLE_SIZE },
    };

    VkWriteDescriptorSet writes[4] = {
        { VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, .dstSet = ds, .dstBinding = 0,
          .descriptorCount = 1, .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
          .pBufferInfo = &bi[0] },
        { VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, .dstSet = ds, .dstBinding = 1,
          .descriptorCount = 1, .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
          .pBufferInfo = &bi[1] },
        { VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, .dstSet = ds, .dstBinding = 2,
          .descriptorCount = 1, .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
          .pBufferInfo = &bi[2] },
        { VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, .dstSet = ds, .dstBinding = 3,
          .descriptorCount = 1, .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
          .pBufferInfo = &bi[3] },
    };

    vkUpdateDescriptorSets(ctx->device, 4, writes, 0, NULL);
}

/* ── Push constants ───────────────────────────────────────────────────────── */

void vkblas_push_pc(VkCommandBuffer cmd, VkPipelineLayout layout,
                    const vkblas_push_constants_t* pc)
{
    vkCmdPushConstants(cmd, layout, VK_SHADER_STAGE_COMPUTE_BIT,
                       0, sizeof(vkblas_push_constants_t), pc);
}

/* ── Context lifecycle ────────────────────────────────────────────────────── */

VkResult vkblas_create_context(VkPhysicalDevice physicalDevice,
                               VkDevice device,
                               VkBLASContext** pContext)
{
    if (!pContext) return VK_ERROR_INITIALIZATION_FAILED;

    VkBLASContext* ctx = (VkBLASContext*)malloc(sizeof(VkBLASContext));
    if (!ctx) return VK_ERROR_OUT_OF_HOST_MEMORY;

    memset(ctx, 0, sizeof(*ctx));
    ctx->device = device;
    ctx->pipeline_cache = VK_NULL_HANDLE;

    /* Create pipeline cache */
    VkPipelineCacheCreateInfo pcci = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO,
    };
    VkResult r = vkCreatePipelineCache(device, &pcci, NULL, &ctx->pipeline_cache);
    if (r != VK_SUCCESS) goto fail;

    /* Create descriptor pool */
    r = vkblas_create_descriptor_pool(ctx);
    if (r != VK_SUCCESS) goto fail;

    /* Create descriptor set layout */
    r = vkblas_create_set_layout(ctx);
    if (r != VK_SUCCESS) goto fail;

    /* Create pipeline layout */
    r = vkblas_create_pipeline_layout(ctx);
    if (r != VK_SUCCESS) goto fail;

    /* Detect capabilities inline (per AGENTS.md: "Capability detection at
       context creation") using the physical device handle. */
    r = vkblas_init_capabilities(ctx, physicalDevice);
    if (r != VK_SUCCESS) {
        /* Fall back to baseline if detection fails */
        ctx->active_tier = VKBLAS_TIER_BASELINE;
        ctx->has_subgroup = VK_FALSE;
        ctx->has_coop_matrix = VK_FALSE;
    }

    *pContext = ctx;
    return VK_SUCCESS;

fail:
    if (ctx->pipeline_cache)
        vkDestroyPipelineCache(device, ctx->pipeline_cache, NULL);
    if (ctx->descriptor_pool)
        vkDestroyDescriptorPool(device, ctx->descriptor_pool, NULL);
    if (ctx->set_layout)
        vkDestroyDescriptorSetLayout(device, ctx->set_layout, NULL);
    if (ctx->pipeline_layout)
        vkDestroyPipelineLayout(device, ctx->pipeline_layout, NULL);
    free(ctx);
    return r;
}

void vkblas_destroy_context(VkBLASContext* context)
{
    if (!context) return;

    for (uint32_t i = 0; i < VKBLAS_MAX_PIPELINES; ++i) {
        if (context->pipelines[i].valid)
            vkDestroyPipeline(context->device, context->pipelines[i].pipeline, NULL);
    }

    if (context->pipeline_cache)
        vkDestroyPipelineCache(context->device, context->pipeline_cache, NULL);
    if (context->descriptor_pool)
        vkDestroyDescriptorPool(context->device, context->descriptor_pool, NULL);
    if (context->set_layout)
        vkDestroyDescriptorSetLayout(context->device, context->set_layout, NULL);
    if (context->pipeline_layout)
        vkDestroyPipelineLayout(context->device, context->pipeline_layout, NULL);

    free(context);
}

uint32_t vkblas_get_arch_index(VkBLASContext* context)
{
    return (uint32_t)context->active_tier;
}

const char* vkblas_get_arch_name(VkBLASContext* context)
{
    switch (context->active_tier) {
    case VKBLAS_TIER_BASELINE:   return "baseline";
    case VKBLAS_TIER_SUBGROUP:   return "subgroup";
    case VKBLAS_TIER_COOPMATRIX: return "coopmatrix";
    default:                     return "unknown";
    }
}

/* ── Capability detection ─────────────────────────────────────────────────── */

VkResult vkblas_init_capabilities(VkBLASContext* ctx, VkPhysicalDevice pd)
{
    /* Check for subgroup support */
    {
        VkPhysicalDeviceSubgroupProperties subgroup_props = {
            .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES,
        };
        VkPhysicalDeviceProperties2 props2 = {
            .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2,
            .pNext = &subgroup_props,
        };
        vkGetPhysicalDeviceProperties2(pd, &props2);
        ctx->max_subgroup_size = subgroup_props.subgroupSize;
        ctx->has_subgroup = (subgroup_props.supportedStages & VK_SHADER_STAGE_COMPUTE_BIT) ? VK_TRUE : VK_FALSE;
        ctx->max_compute_workgroup_size[0] = props2.properties.limits.maxComputeWorkGroupSize[0];
        ctx->max_compute_workgroup_size[1] = props2.properties.limits.maxComputeWorkGroupSize[1];
        ctx->max_compute_workgroup_size[2] = props2.properties.limits.maxComputeWorkGroupSize[2];
    }

    /* Check for cooperative matrix support */
    {
        VkPhysicalDeviceCooperativeMatrixFeaturesKHR coop_features = {
            .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR,
        };
        VkPhysicalDeviceFeatures2 features2 = {
            .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2,
            .pNext = &coop_features,
        };
        vkGetPhysicalDeviceFeatures2(pd, &features2);
        ctx->has_coop_matrix = coop_features.cooperativeMatrix;
    }

    /* Select highest tier */
    if (ctx->has_coop_matrix && ctx->has_subgroup) {
        ctx->active_tier = VKBLAS_TIER_COOPMATRIX;
    } else if (ctx->has_subgroup) {
        ctx->active_tier = VKBLAS_TIER_SUBGROUP;
    } else {
        ctx->active_tier = VKBLAS_TIER_BASELINE;
    }

    return VK_SUCCESS;
}

void vkblas_flush_pipelines(VkBLASContext* ctx)
{
    for (uint32_t i = 0; i < VKBLAS_MAX_PIPELINES; ++i) {
        if (ctx->pipelines[i].valid) {
            vkDestroyPipeline(ctx->device, ctx->pipelines[i].pipeline, NULL);
            ctx->pipelines[i].valid = 0;
        }
    }
    ctx->pipeline_count = 0;
}

/* ── Pointer mode ─────────────────────────────────────────────────────────── */

VkResult vkblas_set_pointer_mode(VkBLASContext* ctx, VkBLASPointerMode_t mode)
{
    if (!ctx) return VK_ERROR_INITIALIZATION_FAILED;
    ctx->pointer_mode = mode;
    return VK_SUCCESS;
}

VkBLASPointerMode_t vkblas_get_pointer_mode(VkBLASContext* ctx)
{
    if (!ctx) return VKBLAS_POINTER_MODE_HOST;
    return ctx->pointer_mode;
}

/* ── GEMM dispatch (f32) ──────────────────────────────────────────────────── */

static VkResult vkblas_sgemm_common(VkBLASContext*  ctx,
                                    VkCommandBuffer  cmd,
                                    VkBLASOperation_t transA,
                                    VkBLASOperation_t transB,
                                    int32_t          m,
                                    int32_t          n,
                                    int32_t          k,
                                    const float*     alpha,
                                    VkBuffer         A,
                                    int32_t          lda,
                                    VkBuffer         B,
                                    int32_t          ldb,
                                    const float*     beta,
                                    VkBuffer         C,
                                    int32_t          ldc,
                                    VkBuffer         D,
                                    int32_t          ldd,
                                    uint32_t         strideA,
                                    uint32_t         strideB,
                                    uint32_t         strideC,
                                    uint32_t         strideD,
                                    int32_t          batchCount,
                                    VkBool32         is_strided)
{
    /* Ensure pipeline exists */
    uint32_t tA = (transA == VKBLAS_OP_N) ? 0 : 1;
    uint32_t tB = (transB == VKBLAS_OP_N) ? 0 : 1;

    VkPipeline pipeline = VK_NULL_HANDLE;
    VkResult r = vkblas_ensure_pipeline(ctx, VKBLAS_DTYPE_F32, tA, tB, is_strided,
                                        &pipeline);
    if (r != VK_SUCCESS)
        return r;

    /* Allocate descriptor set */
    VkDescriptorSet ds;
    r = vkblas_alloc_descriptor_set(ctx, &ds);
    if (r != VK_SUCCESS)
        return r;

    vkblas_write_descriptor_set(ctx, ds, A, B,
                                (C != VK_NULL_HANDLE) ? C : A, D);
    /* Use A as dummy for C when beta==0 (read-only binding won't be accessed) */

    /* Bind pipeline and descriptor set */
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
                            ctx->pipeline_layout, 0, 1, &ds, 0, NULL);

    /* Push constants */
    vkblas_push_constants_t pc = {0};
    pc.m = (uint32_t)m;
    pc.n = (uint32_t)n;
    pc.k = (uint32_t)k;
    pc.alpha = (alpha != NULL) ? *alpha : 1.0f;
    pc.beta = (beta != NULL) ? *beta : 0.0f;
    pc.lda = (uint32_t)lda;
    pc.ldb = (uint32_t)ldb;
    pc.ldc = (uint32_t)ldc;
    pc.ldd = (uint32_t)ldd;
    pc.transA = (int32_t)tA;
    pc.transB = (int32_t)tB;
    pc.beta_is_zero = (pc.beta == 0.0f) ? 1 : 0;
    pc.strideA = strideA;
    pc.strideB = strideB;
    pc.strideC = strideC;
    pc.strideD = strideD;
    pc.batchCount = (uint32_t)batchCount;
    vkblas_push_pc(cmd, ctx->pipeline_layout, &pc);

    /* Compute grid: one workgroup per TILE_M × TILE_N output block */
    uint32_t gridX = (uint32_t)((m + VKBLAS_TILE_M - 1) / VKBLAS_TILE_M);
    uint32_t gridY = (uint32_t)((n + VKBLAS_TILE_N - 1) / VKBLAS_TILE_N);
    uint32_t gridZ = batchCount > 0 ? (uint32_t)batchCount : 1;

    vkCmdDispatch(cmd, gridX, gridY, gridZ);

    return VK_SUCCESS;
}

VkResult vkblas_sgemm(VkBLASContext*  context,
                      VkCommandBuffer cmd,
                      VkBLASOperation_t transA,
                      VkBLASOperation_t transB,
                      int32_t           m,
                      int32_t           n,
                      int32_t           k,
                      const float*      alpha,
                      VkBuffer          A,
                      int32_t           lda,
                      VkBuffer          B,
                      int32_t           ldb,
                      const float*      beta,
                      VkBuffer          C,
                      int32_t           ldc,
                      VkBuffer          D,
                      int32_t           ldd)
{
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0)
        return VK_SUCCESS;  /* no-op for zero-dim matrices */

    return vkblas_sgemm_common(context, cmd, transA, transB,
                               m, n, k, alpha, A, lda, B, ldb,
                               beta, C, ldc, D, ldd,
                               0, 0, 0, 0, 1, VK_FALSE);
}

VkResult vkblas_sgemm_strided_batched(VkBLASContext*    context,
                                      VkCommandBuffer   cmd,
                                      VkBLASOperation_t transA,
                                      VkBLASOperation_t transB,
                                      int32_t           m,
                                      int32_t           n,
                                      int32_t           k,
                                      const float*      alpha,
                                      VkBuffer          A,
                                      int32_t           lda,
                                      int64_t           strideA,
                                      VkBuffer          B,
                                      int32_t           ldb,
                                      int64_t           strideB,
                                      const float*      beta,
                                      VkBuffer          C,
                                      int32_t           ldc,
                                      int64_t           strideC,
                                      VkBuffer          D,
                                      int32_t           ldd,
                                      int64_t           strideD,
                                      int32_t           batchCount)
{
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0 || batchCount <= 0)
        return VK_SUCCESS;

    /* Strides are in bytes in the API but elements in the shader */
    uint32_t elem_strideA = (uint32_t)(strideA / sizeof(float));
    uint32_t elem_strideB = (uint32_t)(strideB / sizeof(float));
    uint32_t elem_strideC = (uint32_t)(strideC / sizeof(float));
    uint32_t elem_strideD = (uint32_t)(strideD / sizeof(float));

    return vkblas_sgemm_common(context, cmd, transA, transB,
                               m, n, k, alpha, A, lda, B, ldb,
                               beta, C, ldc, D, ldd,
                               elem_strideA, elem_strideB,
                               elem_strideC, elem_strideD,
                               batchCount, VK_TRUE);
}

VkResult vkblas_sgemm_batched(VkBLASContext*    context,
                              VkCommandBuffer   cmd,
                              VkBLASOperation_t transA,
                              VkBLASOperation_t transB,
                              int32_t           m,
                              int32_t           n,
                              int32_t           k,
                              const float*      alpha,
                              const VkBLASBufferLoc* A,
                              int32_t           lda,
                              const VkBLASBufferLoc* B,
                              int32_t           ldb,
                              const float*      beta,
                              const VkBLASBufferLoc* C,
                              int32_t           ldc,
                              VkBLASBufferLoc*  D,
                              int32_t           ldd,
                              int32_t           batchCount)
{
    /* Batched GEMM with per-matrix buffer arrays: implement as a loop
       of single GEMMs, each with its own buffer bindings. This is not
       optimal but correct — the caller can use strided_batched for
       better performance when matrices are contiguous. */
    if (!context || !cmd || !A || !B || !D || !alpha || !beta)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (m <= 0 || n <= 0 || k <= 0 || batchCount <= 0)
        return VK_SUCCESS;

    for (int32_t b = 0; b < batchCount; ++b) {
        VkBuffer bufA = (A[b].buffer != VK_NULL_HANDLE) ? A[b].buffer : A->buffer;
        VkBuffer bufB = (B[b].buffer != VK_NULL_HANDLE) ? B[b].buffer : B->buffer;
        VkBuffer bufC = (C && C[b].buffer != VK_NULL_HANDLE) ? C[b].buffer : A->buffer;
        VkBuffer bufD = (D[b].buffer != VK_NULL_HANDLE) ? D[b].buffer : A->buffer;

        VkResult r = vkblas_sgemm_common(context, cmd, transA, transB,
                                         m, n, k, alpha,
                                         bufA, lda, bufB, ldb,
                                         beta, bufC, ldc, bufD, ldd,
                                         0, 0, 0, 0, 1, VK_FALSE);
        if (r != VK_SUCCESS) return r;
    }
    return VK_SUCCESS;
}

/* ── Non-f32 GEMM variants ────────────────────────────────────────────────── *
 * Only the f32 (sgemm) shader tier exists so far. The remaining public GEMM
 * family members are defined here so the public API surface links, but they
 * return VK_ERROR_FEATURE_NOT_PRESENT until their shaders are written.
 * ─────────────────────────────────────────────────────────────────────────── */

VkResult vkblas_dgemm(VkBLASContext* context, VkCommandBuffer cmd,
                      VkBLASOperation_t transA, VkBLASOperation_t transB,
                      int32_t m, int32_t n, int32_t k, const double* alpha,
                      VkBuffer A, int32_t lda, VkBuffer B, int32_t ldb,
                      const double* beta, VkBuffer C, int32_t ldc,
                      VkBuffer D, int32_t ldd) {
    (void)context; (void)cmd; (void)transA; (void)transB; (void)m; (void)n;
    (void)k; (void)alpha; (void)A; (void)lda; (void)B; (void)ldb;
    (void)beta; (void)C; (void)ldc; (void)D; (void)ldd;
    return VK_ERROR_FEATURE_NOT_PRESENT;
}

VkResult vkblas_dgemm_strided_batched(VkBLASContext* context, VkCommandBuffer cmd,
                                      VkBLASOperation_t transA, VkBLASOperation_t transB,
                                      int32_t m, int32_t n, int32_t k, const double* alpha,
                                      VkBuffer A, int32_t lda, int64_t strideA,
                                      VkBuffer B, int32_t ldb, int64_t strideB,
                                      const double* beta, VkBuffer C, int32_t ldc, int64_t strideC,
                                      VkBuffer D, int32_t ldd, int64_t strideD, int32_t batchCount) {
    (void)context; (void)cmd; (void)transA; (void)transB; (void)m; (void)n; (void)k;
    (void)alpha; (void)A; (void)lda; (void)strideA; (void)B; (void)ldb; (void)strideB;
    (void)beta; (void)C; (void)ldc; (void)strideC; (void)D; (void)ldd; (void)strideD; (void)batchCount;
    return VK_ERROR_FEATURE_NOT_PRESENT;
}

VkResult vkblas_hgemm(VkBLASContext* context, VkCommandBuffer cmd,
                      VkBLASOperation_t transA, VkBLASOperation_t transB,
                      int32_t m, int32_t n, int32_t k, const uint16_t* alpha,
                      VkBuffer A, int32_t lda, VkBuffer B, int32_t ldb,
                      const uint16_t* beta, VkBuffer C, int32_t ldc,
                      VkBuffer D, int32_t ldd) {
    (void)context; (void)cmd; (void)transA; (void)transB; (void)m; (void)n;
    (void)k; (void)alpha; (void)A; (void)lda; (void)B; (void)ldb;
    (void)beta; (void)C; (void)ldc; (void)D; (void)ldd;
    return VK_ERROR_FEATURE_NOT_PRESENT;
}

VkResult vkblas_hgemm_strided_batched(VkBLASContext* context, VkCommandBuffer cmd,
                                      VkBLASOperation_t transA, VkBLASOperation_t transB,
                                      int32_t m, int32_t n, int32_t k, const uint16_t* alpha,
                                      VkBuffer A, int32_t lda, int64_t strideA,
                                      VkBuffer B, int32_t ldb, int64_t strideB,
                                      const uint16_t* beta, VkBuffer C, int32_t ldc, int64_t strideC,
                                      VkBuffer D, int32_t ldd, int64_t strideD, int32_t batchCount) {
    (void)context; (void)cmd; (void)transA; (void)transB; (void)m; (void)n; (void)k;
    (void)alpha; (void)A; (void)lda; (void)strideA; (void)B; (void)ldb; (void)strideB;
    (void)beta; (void)C; (void)ldc; (void)strideC; (void)D; (void)ldd; (void)strideD; (void)batchCount;
    return VK_ERROR_FEATURE_NOT_PRESENT;
}

VkResult vkblas_bgemm(VkBLASContext* context, VkCommandBuffer cmd,
                      VkBLASOperation_t transA, VkBLASOperation_t transB,
                      int32_t m, int32_t n, int32_t k, const uint16_t* alpha,
                      VkBuffer A, int32_t lda, VkBuffer B, int32_t ldb,
                      const uint16_t* beta, VkBuffer C, int32_t ldc,
                      VkBuffer D, int32_t ldd) {
    (void)context; (void)cmd; (void)transA; (void)transB; (void)m; (void)n;
    (void)k; (void)alpha; (void)A; (void)lda; (void)B; (void)ldb;
    (void)beta; (void)C; (void)ldc; (void)D; (void)ldd;
    return VK_ERROR_FEATURE_NOT_PRESENT;
}

VkResult vkblas_bgemm_strided_batched(VkBLASContext* context, VkCommandBuffer cmd,
                                      VkBLASOperation_t transA, VkBLASOperation_t transB,
                                      int32_t m, int32_t n, int32_t k, const uint16_t* alpha,
                                      VkBuffer A, int32_t lda, int64_t strideA,
                                      VkBuffer B, int32_t ldb, int64_t strideB,
                                      const uint16_t* beta, VkBuffer C, int32_t ldc, int64_t strideC,
                                      VkBuffer D, int32_t ldd, int64_t strideD, int32_t batchCount) {
    (void)context; (void)cmd; (void)transA; (void)transB; (void)m; (void)n; (void)k;
    (void)alpha; (void)A; (void)lda; (void)strideA; (void)B; (void)ldb; (void)strideB;
    (void)beta; (void)C; (void)ldc; (void)strideC; (void)D; (void)ldd; (void)strideD; (void)batchCount;
    return VK_ERROR_FEATURE_NOT_PRESENT;
}

VkResult vkblas_gemm_ex(VkBLASContext* context, VkCommandBuffer cmd,
                        VkBLASOperation_t transA, VkBLASOperation_t transB,
                        int32_t m, int32_t n, int32_t k, const void* alpha,
                        VkBuffer A, int32_t lda, size_t strideA_element,
                        VkBuffer B, int32_t ldb, size_t strideB_element,
                        const void* beta, VkBuffer C, int32_t ldc, size_t strideC_element,
                        VkBuffer D, int32_t ldd, size_t strideD_element,
                        VkBLASComputeType_t computeType, VkBLASGemmFlags_t flags) {
    (void)context; (void)cmd; (void)transA; (void)transB; (void)m; (void)n; (void)k;
    (void)alpha; (void)A; (void)lda; (void)strideA_element; (void)B; (void)ldb; (void)strideB_element;
    (void)beta; (void)C; (void)ldc; (void)strideC_element; (void)D; (void)ldd; (void)strideD_element;
    (void)computeType; (void)flags;
    return VK_ERROR_FEATURE_NOT_PRESENT;
}

VkResult vkblas_gemm_ex_strided_batched(VkBLASContext* context, VkCommandBuffer cmd,
                                        VkBLASOperation_t transA, VkBLASOperation_t transB,
                                        int32_t m, int32_t n, int32_t k, const void* alpha,
                                        VkBuffer A, int32_t lda, int64_t strideA, size_t strideA_element,
                                        VkBuffer B, int32_t ldb, int64_t strideB, size_t strideB_element,
                                        const void* beta, VkBuffer C, int32_t ldc, int64_t strideC, size_t strideC_element,
                                        VkBuffer D, int32_t ldd, int64_t strideD, size_t strideD_element,
                                        int32_t batchCount, VkBLASComputeType_t computeType, VkBLASGemmFlags_t flags) {
    (void)context; (void)cmd; (void)transA; (void)transB; (void)m; (void)n; (void)k;
    (void)alpha; (void)A; (void)lda; (void)strideA; (void)strideA_element;
    (void)B; (void)ldb; (void)strideB; (void)strideB_element;
    (void)beta; (void)C; (void)ldc; (void)strideC; (void)strideC_element;
    (void)D; (void)ldd; (void)strideD; (void)strideD_element;
    (void)batchCount; (void)computeType; (void)flags;
    return VK_ERROR_FEATURE_NOT_PRESENT;
}
