#!/usr/bin/env python3
"""Embed one or more SPIR-V (.spv) binaries into a C header as static
const uint32_t arrays + byte-length constants.  Usage:

  python spirv_to_header.py out.h NAME1 spv1.spv NAME2 spv2.spv ...

The generated header is included by exactly one translation unit (vaist_blas.c
under VAIST_HAVE_VK_HDR), so `static const` arrays avoid export/link conflicts.
"""
import sys


def main():
    if len(sys.argv) < 2:
        sys.stderr.write("spirv_to_header: output path required\n")
        return 2
    out_path = sys.argv[1]
    args = sys.argv[2:]
    if len(args) % 2 != 0:
        sys.stderr.write("spirv_to_header: expected (name, spv) pairs\n")
        return 2
    parts = [
        "/* Auto-generated by cmake/spirv_to_header.py. Do not edit. */",
        "#ifndef VAIST_BLAS_SPV_H",
        "#define VAIST_BLAS_SPV_H",
        "#include <stdint.h>",
        "#include <stddef.h>",
    ]
    for i in range(0, len(args), 2):
        name = args[i]
        spv_path = args[i + 1]
        with open(spv_path, "rb") as f:
            data = f.read()
        if len(data) % 4 != 0:
            sys.stderr.write("spirv_to_header: %s size not a multiple of 4\n" % spv_path)
            return 2
        words = []
        for j in range(0, len(data), 4):
            w = data[j] | (data[j + 1] << 8) | (data[j + 2] << 16) | (data[j + 3] << 24)
            words.append("0x%08Xu" % w)
        parts.append("static const uint32_t %s[] = { %s };" % (name, ", ".join(words)))
        parts.append("static const size_t %s_len = %d;" % (name, len(data)))
    parts.append("#endif")
    parts.append("")  # trailing newline
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
